-- Quantity conflict: 4 COMPLETED trips permit 4 records under the one-record-per-trip rule.
USE all_my_trips; SET NAMES utf8mb4; START TRANSACTION;
DELIMITER $$
CREATE PROCEDURE seed_local_records()
BEGIN
 DECLARE r INT DEFAULT 1; DECLARE j INT; DECLARE cid INT DEFAULT 1;
 WHILE r<=4 DO INSERT INTO travel_records(travel_record_id,trip_id,user_id,title,content,rating,visibility) VALUES(r,r+10,MOD(r+9,8)+1,CONCAT('완료 여행 기록 ',r),'완료 여행 합성 후기',4.0+r*0.2,IF(MOD(r,2)=1,'PUBLIC','PRIVATE')); INSERT INTO travel_record_images(travel_record_id,image_url,alt_text,sort_order,is_cover) VALUES(r,CONCAT('https://picsum.photos/seed/all-my-trips-record-',r,'-1/1200/800'),'대표 이미지',1,TRUE),(r,CONCAT('https://picsum.photos/seed/all-my-trips-record-',r,'-2/1200/800'),'추가 이미지',2,FALSE); INSERT INTO travel_record_images(travel_record_id,image_url,alt_text,sort_order,is_cover) VALUES(r,CONCAT('https://picsum.photos/seed/all-my-trips-record-',r,'-3/1200/800'),'추가 이미지',3,FALSE),(r,CONCAT('https://picsum.photos/seed/all-my-trips-record-',r,'-4/1200/800'),'추가 이미지',4,FALSE); SET j=1; WHILE j<=4 DO INSERT INTO travel_record_comments(travel_record_comment_id,travel_record_id,user_id,content,status) VALUES(cid,r,MOD(r+j,8)+1,CONCAT('기록 ',r,' 댓글 ',j),'ACTIVE'); SET cid=cid+1; SET j=j+1; END WHILE; INSERT INTO travel_record_comments(travel_record_comment_id,travel_record_id,user_id,parent_comment_id,content,status) VALUES(cid,r,MOD(r+5,8)+1,cid-4,'합성 답글','ACTIVE'); SET cid=cid+1; INSERT INTO travel_record_comments(travel_record_comment_id,travel_record_id,user_id,parent_comment_id,content,status) VALUES(cid,r,MOD(r+6,8)+1,cid-4,'합성 답글',IF(r=4,'HIDDEN','ACTIVE')); SET cid=cid+1; SET j=1; WHILE j<=8 DO INSERT INTO travel_record_likes(travel_record_id,user_id) VALUES(r,j); SET j=j+1; END WHILE; SET r=r+1; END WHILE;
 SET r=1; WHILE r<=12 DO INSERT INTO travel_record_shares(travel_record_id,user_id,channel,shared_at) VALUES(MOD(r-1,4)+1,IF(MOD(r,4)=0,NULL,MOD(r-1,8)+1),ELT(MOD(r-1,4)+1,'LINK','LINK','KAKAO','FACEBOOK'),DATE_ADD('2026-07-20 10:00:00',INTERVAL r HOUR)); SET r=r+1; END WHILE;
 INSERT INTO travel_record_reports(travel_record_id,reporter_user_id,reason,detail,status,processed_by,processed_at,resolution_note) VALUES(1,4,'SPAM','합성 신고 1','PENDING',NULL,NULL,NULL),(2,5,'ABUSE','합성 신고 2','REVIEWING',NULL,NULL,NULL),(3,6,'INAPPROPRIATE','합성 신고 3','RESOLVED',9,NOW(),'관리자 처리'),(4,7,'COPYRIGHT','합성 신고 4','REJECTED',10,NOW(),'관리자 반려'),(1,8,'PRIVACY','합성 신고 5','PENDING',NULL,NULL,NULL),(2,3,'OTHER','합성 신고 6','RESOLVED',9,NOW(),'관리자 처리');
END$$
DELIMITER ;
CALL seed_local_records(); DROP PROCEDURE seed_local_records; COMMIT;
