USE all_my_trips; SET NAMES utf8mb4; START TRANSACTION;
DELIMITER $$
CREATE PROCEDURE seed_local_tickets()
BEGIN
 DECLARE i INT DEFAULT 1; DECLARE rid INT; DECLARE item_id INT DEFAULT 1; DECLARE qty INT; DECLARE pid INT; DECLARE price DECIMAL(15,2); DECLARE pid2 INT; DECLARE price2 DECIMAL(15,2); DECLARE total DECIMAL(15,2); DECLARE pstatus VARCHAR(20); DECLARE ticket_id INT DEFAULT 1;
 WHILE i<=20 DO SET pid=IF(i<=10,i,IF(i<=15,65+i,65+i)); INSERT INTO ticket_products(ticket_product_id,place_id,name,description,sale_start_at,sale_end_at,usage_start_date,usage_end_date,unit_price,currency_code,max_quantity_per_user,status) VALUES(i,pid,CONCAT('모의 관광 티켓 ',i),'합성 상품','2026-07-01','2026-12-20','2026-08-01','2026-12-31',15000+i*1000,'KRW',4,'ON_SALE'); INSERT INTO ticket_inventory VALUES(i,80+i*5,0,0,NOW(6)); SET i=i+1; END WHILE;
 SET rid=1; WHILE rid<=15 DO SET qty=MOD(rid,2)+1; SET pid=MOD(rid-1,20)+1; SET price=15000+pid*1000; SET total=qty*price; IF rid<=5 THEN SET pid2=MOD(rid,20)+1; SET price2=15000+pid2*1000; SET total=total+price2; END IF; INSERT INTO reservations(reservation_id,reservation_number,user_id,status,total_amount,currency_code,expires_at,confirmed_at,cancelled_at) VALUES(rid,CONCAT('AMT-2026-',LPAD(rid,5,'0')),MOD(rid-1,8)+1,CASE WHEN rid<=5 THEN 'PENDING' WHEN rid<=12 THEN 'CONFIRMED' ELSE 'CANCELLED' END,total,'KRW',IF(rid<=5,'2026-07-25 12:00:00',NULL),IF(rid BETWEEN 6 AND 12,'2026-07-24 11:00:00',NULL),IF(rid>=13,'2026-07-24 11:30:00',NULL)); INSERT INTO reservation_items(reservation_item_id,reservation_id,ticket_product_id,product_name,usage_date,quantity,unit_price,line_amount) VALUES(item_id,rid,pid,CONCAT('모의 관광 티켓 ',pid),'2026-09-15',qty,price,qty*price); IF rid<=5 THEN SET item_id=item_id+1; INSERT INTO reservation_items(reservation_item_id,reservation_id,ticket_product_id,product_name,usage_date,quantity,unit_price,line_amount) VALUES(item_id,rid,pid2,CONCAT('모의 관광 티켓 ',pid2),'2026-09-15',1,price2,price2); END IF; SET pstatus=CASE WHEN rid<=5 THEN IF(MOD(rid,2)=0,'FAILED','READY') WHEN rid<=12 THEN 'PAID' ELSE IF(MOD(rid,2)=0,'REFUNDED','CANCELLED') END; INSERT INTO payments(payment_id,reservation_id,provider,provider_payment_key,method,status,amount,currency_code,failure_code,failure_message,requested_at,approved_at,cancelled_at) VALUES(rid,rid,'MOCK',CONCAT('MOCK-PAY-',LPAD(rid,5,'0')),'CARD',pstatus,total,'KRW',IF(pstatus='FAILED','MOCK_FAILURE',NULL),IF(pstatus='FAILED','모의 실패',NULL),'2026-07-24 10:00:00',IF(pstatus='PAID','2026-07-24 10:01:00',NULL),IF(pstatus IN('CANCELLED','REFUNDED'),'2026-07-24 11:30:00',NULL)); IF rid BETWEEN 6 AND 12 THEN SET i=1; WHILE i<=qty DO INSERT INTO issued_tickets(issued_ticket_id,reservation_item_id,ticket_number,verification_token_hash,issue_method,status,valid_from,valid_until,issued_at) VALUES(ticket_id,item_id,CONCAT('AMT-TICKET-',LPAD(ticket_id,6,'0')),SHA2(CONCAT('synthetic-token-',ticket_id),256),IF(MOD(ticket_id,3)=0,'PRINT','MOBILE'),'ISSUED','2026-09-15','2026-09-15 23:59:59','2026-07-24 10:02:00'); SET ticket_id=ticket_id+1; SET i=i+1; END WHILE; END IF; SET item_id=item_id+1; SET rid=rid+1; END WHILE;
 UPDATE issued_tickets SET status='USED',used_at='2026-09-15 10:00:00' WHERE issued_ticket_id=1; UPDATE issued_tickets SET status='CANCELLED',cancelled_at='2026-08-01 09:00:00' WHERE issued_ticket_id=2; SET i=1; WHILE i<=20 DO INSERT INTO ticket_validation_logs(issued_ticket_id,validator_user_id,presented_token_fingerprint,validation_result,validation_channel,device_id,failure_reason,metadata,validated_at) VALUES(IF(MOD(i,5)=0,NULL,MOD(i-1,ticket_id-1)+1),IF(MOD(i,3)=0,10,9),SHA2(CONCAT('presented-',i),256),ELT(MOD(i-1,5)+1,'SUCCESS','ALREADY_USED','CANCELLED','EXPIRED','NOT_FOUND'),IF(MOD(i,2)=0,'MOCK_SCANNER','ADMIN_WEB'),CONCAT('mock-device-',MOD(i,3)+1),IF(MOD(i-1,5)=0,NULL,'모의 검표 결과'),JSON_OBJECT('synthetic',TRUE),DATE_ADD('2026-09-15 10:00:00',INTERVAL i MINUTE)); SET i=i+1; END WHILE;
END$$
DELIMITER ;
CALL seed_local_tickets(); DROP PROCEDURE seed_local_tickets; COMMIT;
