spring.docker.compose.enabled=false
spring.autoconfigure.exclude=\
org.springframework.boot.data.redis.autoconfigure.DataRedisAutoConfiguration,\
org.springframework.boot.data.redis.autoconfigure.DataRedisReactiveAutoConfiguration,\
org.springframework.boot.data.redis.autoconfigure.DataRedisRepositoriesAutoConfiguration,\
org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration,\
org.springframework.ai.model.google.genai.autoconfigure.embedding.GoogleGenAiEmbeddingConnectionAutoConfiguration,\
org.springframework.ai.model.google.genai.autoconfigure.embedding.GoogleGenAiTextEmbeddingAutoConfiguration,\
org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

spring.datasource.url=jdbc:mysql://localhost:3306/all_my_trip?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=allmytrip
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=org.example.all_my_trip_project.domain
mybatis.configuration.map-underscore-to-camel-case=true

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false

spring.ai.model.chat=none
spring.ai.model.embedding.text=none
