-- All My Trips Flyway migration: V11__accommodation_booking
-- Target: PostgreSQL 16+
--
-- 항공(V9)과 같은 원칙이다. 우리는 숙박을 팔지 않는다. 결제는 숙소·여행사 페이지에서
-- 일어나므로 "예약 완료" 상태를 저장할 수 없고, user_reported_booked(자가 신고) +
-- booking_ref(예약번호)에서 상태를 파생한다.
--
-- 항공과 다른 점은 구간 모델이다. 항공은 가는 편·오는 편 둘로 끝나 UNIQUE(trip_id, leg)로
-- 잠글 수 있었지만, 숙박은 박 수가 여행 일수에 따라 달라지고 도시를 옮기면 한 여행에
-- 여러 건이 붙는다. 그래서 leg 대신 날짜 구간(check_in, check_out)으로 표현한다.

CREATE TABLE accommodation_bookings (
    accommodation_booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id                  BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    user_id                  BIGINT NOT NULL REFERENCES users(user_id),

    check_in                 DATE NOT NULL,
    check_out                DATE NOT NULL,

    offer_id                 VARCHAR(128) NOT NULL,
    provider                 VARCHAR(32) NOT NULL,

    -- 숙소 스냅샷. 조회 시점에 provider를 다시 태우면 이름·주소가 바뀌었을 때
    -- 과거 선택의 표기가 따라 바뀐다. 항공에서 carrier_name을 박제한 것과 같은 이유다.
    name                     VARCHAR(200) NOT NULL,
    accommodation_type       VARCHAR(20) NOT NULL,
    area_label               VARCHAR(100),
    address                  VARCHAR(500),
    rating                   NUMERIC(2,1) CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5)),
    -- 좌표는 나중에 일정 동선 적합도를 계산할 때 쓴다. TourAPI가 제공한다.
    latitude                 NUMERIC(10,7),
    longitude                NUMERIC(10,7),

    -- 요금 스냅샷. 표시 요금은 실시간으로 바뀌므로 선택 시점 값을 박제한다.
    -- 재검색해도 덮어쓰지 않는다. 어디에도 "결제 금액"으로 표시하지 않는다.
    -- TourAPI는 요금을 주지 않으므로 값 없이 출처만 UNAVAILABLE로 남는 경우가 많다.
    quoted_nightly_price     NUMERIC(12,2) CHECK (quoted_nightly_price IS NULL OR quoted_nightly_price >= 0),
    quoted_total_price       NUMERIC(12,2) CHECK (quoted_total_price IS NULL OR quoted_total_price >= 0),
    quoted_currency          CHAR(3) NOT NULL DEFAULT 'KRW',
    -- 이때 본 값이 정가였는지 제휴사 판매가였는지 실습용이었는지 못 밝히면 CS 대응이 불가능해진다.
    quoted_price_source      VARCHAR(16) NOT NULL,
    quoted_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    rooms                    SMALLINT NOT NULL DEFAULT 1 CHECK (rooms > 0),
    adults                   SMALLINT NOT NULL DEFAULT 2 CHECK (adults > 0),

    -- 사용자가 "예약했다"고 직접 표시한 값. 결제 확인이 아니다.
    user_reported_booked     BOOLEAN NOT NULL DEFAULT FALSE,
    user_reported_at         TIMESTAMPTZ,

    -- 예약번호가 들어오면 확정으로 승격한다.
    booking_ref              VARCHAR(32),
    booking_ref_added_at     TIMESTAMPTZ,

    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_accommodation_bookings_period CHECK (check_out > check_in),
    CONSTRAINT ck_accommodation_bookings_price_source
        CHECK (quoted_price_source IN ('RACK', 'PARTNER', 'SANDBOX', 'UNAVAILABLE', 'MOCK')),
    -- 요금이 없으면 출처가 UNAVAILABLE이어야 한다. 0원으로 저장해 최저가로 보이는 일을 막는다.
    CONSTRAINT ck_accommodation_bookings_price_presence
        CHECK (quoted_total_price IS NOT NULL OR quoted_price_source = 'UNAVAILABLE')
);

-- 같은 여행에 같은 기간의 숙소를 두 번 넣지 않는다.
-- 날짜가 겹치는(포함 관계인) 경우까지 막으려면 btree_gist 확장과 EXCLUDE 제약이 필요한데,
-- 확장을 하나 더 늘리는 대신 애플리케이션에서 검증한다. 한 사용자가 자기 여행을 편집하는
-- 상황이라 동시성 위험이 낮다. 더 엄격하게 가야 하면 그때 EXCLUDE로 올린다.
CREATE UNIQUE INDEX uk_accommodation_bookings_trip_period
    ON accommodation_bookings(trip_id, check_in, check_out);

CREATE INDEX idx_accommodation_bookings_user ON accommodation_bookings(user_id, trip_id);

CREATE TRIGGER trg_accommodation_bookings_updated_at BEFORE UPDATE ON accommodation_bookings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 외부 예약 사이트로 나간 이력.
-- 복귀 감지(visibilitychange)는 놓칠 수 있으므로, 놓친 건을 다음 방문에 다시 물어보려면
-- 이 로그가 있어야 한다. 항공의 flight_outbound_clicks와 같은 역할이다.
--
-- 항공은 leg로 어느 구간의 이탈인지 가리켰지만 숙박은 건수가 가변이라
-- 저장된 예약 행을 직접 참조한다. 예약이 지워지면 이력도 함께 지운다 —
-- 어느 숙소에 대한 질문인지 알 수 없는 재질문은 물어볼 수 없다.
CREATE TABLE accommodation_outbound_clicks (
    accommodation_outbound_click_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accommodation_booking_id        BIGINT NOT NULL
        REFERENCES accommodation_bookings(accommodation_booking_id) ON DELETE CASCADE,
    user_id      BIGINT NOT NULL REFERENCES users(user_id),
    trip_id      BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    offer_id     VARCHAR(128) NOT NULL,
    provider     VARCHAR(32) NOT NULL,
    deeplink_url TEXT NOT NULL,
    clicked_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- visibilitychange 감지 시각. 알림 확인·앱 전환에도 발생하므로 부정확할 수 있다.
    returned_at  TIMESTAMPTZ,
    outcome      VARCHAR(16),

    CONSTRAINT ck_accommodation_outbound_clicks_outcome
        CHECK (outcome IS NULL OR outcome IN ('REPORTED_YES', 'REPORTED_NO', 'LATER', 'NO_RESPONSE'))
);
CREATE INDEX idx_accommodation_outbound_clicks_booking
    ON accommodation_outbound_clicks(accommodation_booking_id, clicked_at DESC);
-- 무응답 재질문 배너가 이 인덱스로 조회한다.
CREATE INDEX idx_accommodation_outbound_clicks_pending
    ON accommodation_outbound_clicks(trip_id, outcome);
