-- 장소별 방문자 후기
CREATE TABLE place_reviews (
    place_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id        BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    rating          SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content         VARCHAR(1000) NOT NULL,
    verified_visit  BOOLEAN NOT NULL DEFAULT FALSE,
    status          VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_reviews_user_place UNIQUE (place_id, user_id),
    CONSTRAINT ck_place_reviews_status CHECK (status IN ('VISIBLE', 'HIDDEN'))
);

CREATE INDEX idx_place_reviews_place_created
    ON place_reviews(place_id, created_at DESC, place_review_id DESC)
    WHERE status = 'VISIBLE';

CREATE TRIGGER trg_place_reviews_updated_at
BEFORE UPDATE ON place_reviews
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE place_reviews IS 'User ratings and reviews for individual places';
