-- Customer support inquiries and administrator replies.
CREATE TABLE support_inquiries (
    support_inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category           VARCHAR(30) NOT NULL,
    title              VARCHAR(150) NOT NULL,
    content            VARCHAR(3000) NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_support_inquiries_category CHECK (category IN (
        'TRIP_PLAN', 'AI_PLAN', 'PLACE_FAVORITE', 'BOOKING', 'ACCOUNT', 'ERROR', 'OTHER'
    )),
    CONSTRAINT ck_support_inquiries_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'ANSWERED', 'CLOSED'))
);
CREATE INDEX idx_support_inquiries_user_created
    ON support_inquiries(user_id, created_at DESC);
CREATE INDEX idx_support_inquiries_status_created
    ON support_inquiries(status, created_at ASC);
CREATE TRIGGER trg_support_inquiries_updated_at BEFORE UPDATE ON support_inquiries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE support_replies (
    support_reply_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_inquiry_id BIGINT NOT NULL REFERENCES support_inquiries(support_inquiry_id) ON DELETE CASCADE,
    admin_user_id      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    content            VARCHAR(3000) NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_support_replies_inquiry_created
    ON support_replies(support_inquiry_id, created_at);

COMMENT ON TABLE support_inquiries IS 'Customer support inquiries submitted by members';
COMMENT ON TABLE support_replies IS 'Administrator replies to customer support inquiries';
