-- Administrator replies for customer support inquiries.
-- V14 is already immutable and V15 deliberately removed this table, so the
-- administrator support feature restores it in a new migration.
CREATE TABLE support_replies (
    support_reply_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_inquiry_id BIGINT NOT NULL REFERENCES support_inquiries(support_inquiry_id) ON DELETE CASCADE,
    admin_user_id      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    content            VARCHAR(3000) NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_support_replies_inquiry_created
    ON support_replies(support_inquiry_id, created_at);

COMMENT ON TABLE support_replies IS 'Administrator replies to customer support inquiries';
