-- 상담 채팅 (#247)
--
-- 1:1 문의(support_inquiries)와 나란히 둔다. 성격이 다르다 — 문의는 한 번 남기고 답변을
-- 기다리는 것이고, 상담은 지금 붙어서 여러 번 주고받는 것이다.
--
-- 챗봇이 들어올 자리를 미리 비워 둔다. 봇은 나중에 "메시지를 쓰는 참여자 하나"로 들어오므로
-- sender_type에 BOT을, 방 상태에 BOT을 처음부터 넣는다. 봇이 없는 동안은 그 값의 행이
-- 생기지 않을 뿐이다. 나중에 컬럼을 늘리면 이미 쌓인 데이터를 손봐야 한다.

CREATE TABLE support_chat_rooms (
    support_chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    -- 담당 관리자. 계정이 지워져도 상담 기록은 남아야 하므로 SET NULL이다.
    assigned_admin_id    BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    -- 목록을 최근 대화순으로 세우려면 방마다 들고 있어야 한다. 메시지를 매번 세면 느리다.
    last_message_at      TIMESTAMPTZ,
    assigned_at          TIMESTAMPTZ,
    closed_at            TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 상태 전이 자체(어떤 상태에서 어떤 상태로 갈 수 있는가)는 DB가 강제하지 않고
    -- SupportChatMapper.xml의 UPDATE 문 WHERE 절이 맡는다(예: returnToBot은
    -- WHERE status = 'WAITING'). 여기서는 값의 집합만 막는다.
    -- docs/support-chat-ai-websocket.md "8. 상태 전이"에 전체 상태 기계가 있다.
    CONSTRAINT ck_support_chat_rooms_status
        CHECK (status IN ('BOT', 'WAITING', 'ASSIGNED', 'CLOSED')),
    -- 배정된 방에는 담당자가 있어야 하고, 그 밖의 상태에는 없어야 한다.
    CONSTRAINT ck_support_chat_rooms_assignee
        CHECK ((status = 'ASSIGNED') = (assigned_admin_id IS NOT NULL))
);

-- 손님당 열린 방은 하나로 제한한다. 여러 개면 관리자가 같은 사람과 여러 창구에서
-- 이야기하게 되고, 손님도 어느 창에 답이 왔는지 알 수 없다.
-- 종료된 방은 제한하지 않으므로 부분 유니크 인덱스를 쓴다.
CREATE UNIQUE INDEX uk_support_chat_rooms_open_user
    ON support_chat_rooms(user_id) WHERE status <> 'CLOSED';

-- 관리자 화면이 상태로 거르고 최근 대화순으로 세운다.
CREATE INDEX idx_support_chat_rooms_status_recent
    ON support_chat_rooms(status, last_message_at DESC NULLS LAST);
CREATE INDEX idx_support_chat_rooms_assignee_recent
    ON support_chat_rooms(assigned_admin_id, last_message_at DESC NULLS LAST);

CREATE TRIGGER trg_support_chat_rooms_updated_at BEFORE UPDATE ON support_chat_rooms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE support_chat_messages (
    support_chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_chat_room_id    BIGINT NOT NULL
        REFERENCES support_chat_rooms(support_chat_room_id) ON DELETE CASCADE,
    sender_type             VARCHAR(10) NOT NULL,
    -- 봇이 쓴 메시지는 보낸이가 없다. 그래서 NULL을 허용한다.
    sender_user_id          BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    content                 VARCHAR(2000) NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_support_chat_messages_sender
        CHECK (sender_type IN ('USER', 'BOT', 'ADMIN')),
    -- 봇이 아닌 메시지에는 보낸이가 반드시 있어야 한다.
    CONSTRAINT ck_support_chat_messages_sender_user
        CHECK (sender_type = 'BOT' OR sender_user_id IS NOT NULL)
);

-- 대화창은 한 방의 메시지를 시간순으로 읽는다.
CREATE INDEX idx_support_chat_messages_room_time
    ON support_chat_messages(support_chat_room_id, support_chat_message_id);

COMMENT ON TABLE support_chat_rooms IS 'Live support chat rooms; one open room per user';
COMMENT ON TABLE support_chat_messages IS 'Messages exchanged in a support chat room';
