-- All My Trips Flyway migration: V1__member_and_place
-- Target: PostgreSQL 16+ / UTF-8

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END;
$$;

CREATE TABLE users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          CITEXT NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    nickname       VARCHAR(50) NOT NULL UNIQUE,
    role           VARCHAR(20) NOT NULL DEFAULT 'USER',
    status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_styles (
    travel_style_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(30) NOT NULL UNIQUE,
    name             VARCHAR(50) NOT NULL UNIQUE,
    description      VARCHAR(500),
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order       SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_travel_styles_updated_at BEFORE UPDATE ON travel_styles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_preferences (
    user_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    travel_style_id     SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    preference_score    SMALLINT NOT NULL DEFAULT 50 CHECK (preference_score BETWEEN 0 AND 100),
    source              VARCHAR(20) NOT NULL DEFAULT 'EXPLICIT',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_preferences_user_style UNIQUE (user_id, travel_style_id),
    CONSTRAINT ck_user_preferences_source CHECK (source IN ('EXPLICIT', 'INFERRED'))
);
CREATE INDEX idx_user_preferences_style_score ON user_preferences(travel_style_id, preference_score DESC);
CREATE TRIGGER trg_user_preferences_updated_at BEFORE UPDATE ON user_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE places (
    place_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_provider  VARCHAR(30),
    external_place_id  VARCHAR(100),
    category           VARCHAR(30) NOT NULL,
    name               VARCHAR(150) NOT NULL,
    country_code       CHAR(2) NOT NULL,
    region             VARCHAR(100),
    city               VARCHAR(100),
    address            VARCHAR(255),
    latitude           NUMERIC(10,7),
    longitude          NUMERIC(10,7),
    description        TEXT,
    phone              VARCHAR(50),
    website_url        VARCHAR(500),
    average_rating     NUMERIC(3,2),
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_places_external UNIQUE (external_provider, external_place_id),
    CONSTRAINT ck_places_category CHECK (category IN ('ATTRACTION', 'RESTAURANT', 'CAFE', 'ACCOMMODATION', 'FESTIVAL', 'ACTIVITY', 'TRANSPORT')),
    CONSTRAINT ck_places_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_places_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_places_rating CHECK (average_rating IS NULL OR average_rating BETWEEN 0 AND 5),
    CONSTRAINT ck_places_external_pair CHECK ((external_provider IS NULL) = (external_place_id IS NULL))
);
CREATE INDEX idx_places_search ON places(country_code, region, city, category, is_active);
CREATE INDEX idx_places_name ON places(name);
CREATE TRIGGER trg_places_updated_at BEFORE UPDATE ON places
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE place_images (
    place_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id       BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    image_url      VARCHAR(1000) NOT NULL,
    alt_text       VARCHAR(255),
    sort_order     SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    is_primary     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_images_order UNIQUE (place_id, sort_order)
);
CREATE UNIQUE INDEX uk_place_images_one_primary ON place_images(place_id) WHERE is_primary;

CREATE TABLE place_travel_styles (
    place_travel_style_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id              BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    travel_style_id       SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    relevance_score       SMALLINT NOT NULL CHECK (relevance_score BETWEEN 0 AND 100),
    source                VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_travel_styles UNIQUE (place_id, travel_style_id),
    CONSTRAINT ck_place_travel_styles_source CHECK (source IN ('MANUAL', 'AI', 'IMPORT'))
);
CREATE INDEX idx_place_travel_styles_rank ON place_travel_styles(travel_style_id, relevance_score DESC);
CREATE TRIGGER trg_place_travel_styles_updated_at BEFORE UPDATE ON place_travel_styles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    place_id    BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    memo        VARCHAR(500),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorites_user_place UNIQUE (user_id, place_id)
);
CREATE INDEX idx_favorites_user_created ON favorites(user_id, created_at DESC);

COMMENT ON TABLE users IS 'Member accounts';
COMMENT ON TABLE travel_styles IS 'Travel style code dictionary';
COMMENT ON TABLE user_preferences IS 'Per-user travel style preferences';
COMMENT ON TABLE places IS 'Searchable travel places';
COMMENT ON TABLE place_images IS 'Place image metadata';
COMMENT ON TABLE place_travel_styles IS 'Travel style relevance tags for places';
COMMENT ON TABLE favorites IS 'Places saved by users';
