-- 알림. 마이페이지 사이드바의 `알림`이 이 표를 읽습니다.
--
-- 지금까지 화면에 버튼만 `준비 중`으로 놓여 있고 표도 코드도 없었습니다.
--
-- 알림은 만들어질 때의 문구를 그대로 담습니다. 예약이나 문의를 조인해서 그때그때
-- 문장을 만들지 않습니다. 원본이 지워지거나 바뀌어도 손님이 받은 알림은 그대로여야
-- 하고, 목록을 그릴 때마다 여러 표를 조인하면 알림이 늘수록 느려집니다.
CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,

    -- 알림 종류. 화면이 이 값으로 아이콘을 고릅니다.
    type            VARCHAR(30) NOT NULL,

    title           VARCHAR(100) NOT NULL,
    body            VARCHAR(500),

    -- 눌렀을 때 갈 곳. 우리 사이트 안의 경로만 담습니다.
    link            VARCHAR(300),

    read_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_notifications_type
        CHECK (type IN ('PAYMENT_COMPLETED', 'SUPPORT_REPLIED')),
    CONSTRAINT ck_notifications_link_internal
        -- 바깥 주소를 담아 두면 알림이 손님을 사이트 밖으로 보내는 발판이 됩니다.
        CHECK (link IS NULL OR (link LIKE '/%' AND link NOT LIKE '//%'))
);

-- 목록은 늘 "내 알림을 최신순으로"입니다. 안 읽은 개수도 이 인덱스로 셉니다.
CREATE INDEX idx_notifications_user_created
    ON notifications(user_id, created_at DESC);

COMMENT ON TABLE notifications IS 'In-app notifications shown in the member mypage';
COMMENT ON COLUMN notifications.type IS 'Notification kind used to pick an icon';
COMMENT ON COLUMN notifications.link IS 'Internal path to open when the notification is clicked';
COMMENT ON COLUMN notifications.read_at IS 'When the member read it. NULL means unread';
