-- 마이페이지 "최근 본 여행지"를 위한 조회 이력.
--
-- 지금까지 이 패널은 "최근에 조회한 여행지가 없어요" 빈 상태가 화면에 박혀 있을 뿐,
-- 기록하는 곳도 읽는 곳도 없었다.
--
-- 브라우저(localStorage)가 아니라 서버에 남긴다. 이 패널은 로그인해야 들어가는
-- 마이페이지 안에 있어서, 기기별로 다른 목록이 보이면 같은 계정인데 결과가 달라진다.
--
-- recommendation_events를 재활용하지 않는 이유: 그쪽은 recommendation_result_id를
-- 참조해 추천 화면을 거친 클릭만 담긴다. 검색이나 일정에서 들어간 조회는 빠진다.
CREATE TABLE place_view_history (
    place_view_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users(user_id)   ON DELETE CASCADE,
    place_id              BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    viewed_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 같은 장소를 열 번 봐도 행은 하나다. 목록이 같은 장소로 도배되지 않고,
    -- 사용자당 행 수가 그 사람이 본 장소 수를 넘지 않는다.
    CONSTRAINT uk_place_view_history_user_place UNIQUE (user_id, place_id)
);

-- 목록은 항상 "내 것을 최근 순으로 N개"라서 이 순서 그대로 태운다.
CREATE INDEX idx_place_view_history_user_viewed
    ON place_view_history(user_id, viewed_at DESC);

COMMENT ON TABLE place_view_history IS 'Places each member recently opened, newest view per place';
COMMENT ON COLUMN place_view_history.viewed_at IS 'Last time the member opened this place detail';
