-- All My Trips Flyway migration: V2__trip_and_itinerary
-- Target: PostgreSQL 16+

CREATE TABLE trips (
    trip_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users(user_id),
    title                 VARCHAR(150) NOT NULL,
    destination_name      VARCHAR(150) NOT NULL,
    start_date             DATE NOT NULL,
    end_date               DATE NOT NULL,
    companion_type        VARCHAR(20) NOT NULL,
    companion_count       SMALLINT NOT NULL DEFAULT 1 CHECK (companion_count > 0),
    purpose                VARCHAR(500),
    budget_amount          NUMERIC(15,2) CHECK (budget_amount IS NULL OR budget_amount >= 0),
    currency_code          CHAR(3) NOT NULL DEFAULT 'KRW',
    transport_preference   VARCHAR(100),
    food_preference        VARCHAR(255),
    pace                   VARCHAR(20),
    accommodation_style    VARCHAR(100),
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    source                 VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at             TIMESTAMPTZ,
    CONSTRAINT ck_trips_period CHECK (end_date >= start_date),
    CONSTRAINT ck_trips_companion CHECK (companion_type IN ('SOLO', 'FRIENDS', 'COUPLE', 'FAMILY', 'GROUP', 'OTHER')),
    CONSTRAINT ck_trips_pace CHECK (pace IS NULL OR pace IN ('RELAXED', 'NORMAL', 'PACKED')),
    CONSTRAINT ck_trips_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_trips_source CHECK (source IN ('MANUAL', 'AI'))
);
CREATE INDEX idx_trips_user_status_dates ON trips(user_id, status, start_date, end_date);
CREATE TRIGGER trg_trips_updated_at BEFORE UPDATE ON trips
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE trip_travel_styles (
    trip_id         BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    travel_style_id SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    priority        SMALLINT NOT NULL DEFAULT 1 CHECK (priority > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (trip_id, travel_style_id),
    CONSTRAINT uk_trip_travel_styles_priority UNIQUE (trip_id, priority)
);

CREATE TABLE trip_days (
    trip_day_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id     BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    day_number  SMALLINT NOT NULL CHECK (day_number > 0),
    trip_date   DATE NOT NULL,
    title       VARCHAR(150),
    memo        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_trip_days_number UNIQUE (trip_id, day_number),
    CONSTRAINT uk_trip_days_date UNIQUE (trip_id, trip_date)
);
CREATE TRIGGER trg_trip_days_updated_at BEFORE UPDATE ON trip_days
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE itinerary_items (
    itinerary_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_day_id       BIGINT NOT NULL REFERENCES trip_days(trip_day_id) ON DELETE CASCADE,
    place_id          BIGINT REFERENCES places(place_id) ON DELETE SET NULL,
    item_type         VARCHAR(30) NOT NULL,
    title             VARCHAR(150) NOT NULL,
    start_time        TIME,
    end_time          TIME,
    sort_order        SMALLINT NOT NULL CHECK (sort_order >= 0),
    memo              TEXT,
    estimated_cost    NUMERIC(15,2) CHECK (estimated_cost IS NULL OR estimated_cost >= 0),
    currency_code     CHAR(3) NOT NULL DEFAULT 'KRW',
    source            VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_itinerary_items_order UNIQUE (trip_day_id, sort_order),
    CONSTRAINT ck_itinerary_items_type CHECK (item_type IN ('PLACE', 'MEAL', 'ACCOMMODATION', 'TRANSPORT', 'ACTIVITY', 'NOTE')),
    CONSTRAINT ck_itinerary_items_period CHECK (end_time IS NULL OR start_time IS NULL OR end_time >= start_time),
    CONSTRAINT ck_itinerary_items_source CHECK (source IN ('MANUAL', 'AI'))
);
CREATE INDEX idx_itinerary_items_place ON itinerary_items(place_id);
CREATE TRIGGER trg_itinerary_items_updated_at BEFORE UPDATE ON itinerary_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE trip_share_links (
    trip_share_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    created_by         BIGINT NOT NULL REFERENCES users(user_id),
    token_hash         CHAR(64) NOT NULL UNIQUE,
    permission         VARCHAR(20) NOT NULL DEFAULT 'VIEW',
    expires_at         TIMESTAMPTZ,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_share_links_permission CHECK (permission IN ('VIEW')),
    CONSTRAINT ck_trip_share_links_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
);
CREATE INDEX idx_trip_share_links_trip_active ON trip_share_links(trip_id, revoked_at, expires_at);

COMMENT ON TABLE trips IS 'User travel plans and input conditions';
COMMENT ON TABLE trip_travel_styles IS 'Travel styles selected for a trip';
COMMENT ON TABLE trip_days IS 'Daily sections of a trip';
COMMENT ON TABLE itinerary_items IS 'Ordered activities within a trip day';
COMMENT ON TABLE trip_share_links IS 'Revocable read-only links for the schedule share screen';
