-- 비밀번호 재설정 링크에 담는 토큰.
--
-- 원문은 저장하지 않고 SHA-256 해시만 둔다. DB가 새더라도 그 값으로 남의 비밀번호를
-- 바꿀 수 없어야 한다. 확인할 때는 받은 토큰을 같은 방식으로 해시해서 맞춰 본다.
--
-- 한 번 쓰면 used_at을 채워 다시 못 쓰게 한다. 링크가 메일함에 남아 있어도 두 번째
-- 부터는 통하지 않는다.

CREATE TABLE password_reset_tokens (
    password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash              CHAR(64) NOT NULL,
    expires_at              TIMESTAMPTZ NOT NULL,
    used_at                 TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_password_reset_tokens_hash UNIQUE (token_hash)
);

COMMENT ON COLUMN password_reset_tokens.token_hash IS
    'SHA-256 해시. 링크에 담긴 원문은 저장하지 않는다';
COMMENT ON COLUMN password_reset_tokens.used_at IS
    '비밀번호를 바꾼 시각. 채워지면 그 토큰은 다시 쓸 수 없다';

-- 새 링크를 보낼 때 그 사람의 이전 토큰을 한꺼번에 무르려면 사용자로 찾아야 한다.
CREATE INDEX idx_password_reset_tokens_user
    ON password_reset_tokens(user_id, created_at DESC);
