-- All My Trips Flyway migration: V3__ai_and_recommendation
-- Target: PostgreSQL 16+

CREATE TABLE ai_chat_sessions (
    ai_chat_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    trip_id            BIGINT REFERENCES trips(trip_id) ON DELETE SET NULL,
    title              VARCHAR(150),
    status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_at    TIMESTAMPTZ,
    CONSTRAINT ck_ai_chat_sessions_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);
CREATE INDEX idx_ai_chat_sessions_user_recent ON ai_chat_sessions(user_id, last_message_at DESC NULLS LAST);
CREATE TRIGGER trg_ai_chat_sessions_updated_at BEFORE UPDATE ON ai_chat_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ai_generation_requests (
    ai_generation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT NOT NULL REFERENCES users(user_id),
    trip_id                   BIGINT REFERENCES trips(trip_id) ON DELETE SET NULL,
    ai_chat_session_id        BIGINT REFERENCES ai_chat_sessions(ai_chat_session_id) ON DELETE SET NULL,
    request_type              VARCHAR(30) NOT NULL,
    provider                  VARCHAR(50) NOT NULL,
    model_name                VARCHAR(100) NOT NULL,
    prompt_version            VARCHAR(50) NOT NULL,
    input_payload             JSONB NOT NULL,
    output_payload            JSONB,
    status                    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    error_message             VARCHAR(1000),
    input_tokens              INTEGER CHECK (input_tokens IS NULL OR input_tokens >= 0),
    output_tokens             INTEGER CHECK (output_tokens IS NULL OR output_tokens >= 0),
    requested_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at              TIMESTAMPTZ,
    CONSTRAINT ck_ai_generation_requests_type CHECK (request_type IN ('CREATE_ITINERARY', 'RECOMMEND_PLACES', 'OPTIMIZE_ROUTE', 'CHAT')),
    CONSTRAINT ck_ai_generation_requests_status CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_ai_generation_requests_period CHECK (completed_at IS NULL OR completed_at >= requested_at)
);
CREATE INDEX idx_ai_generation_requests_user_time ON ai_generation_requests(user_id, requested_at DESC);
CREATE INDEX idx_ai_generation_requests_trip_type ON ai_generation_requests(trip_id, request_type);
CREATE INDEX idx_ai_generation_requests_status ON ai_generation_requests(status, requested_at);

CREATE TABLE ai_chat_messages (
    ai_chat_message_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_chat_session_id       BIGINT NOT NULL REFERENCES ai_chat_sessions(ai_chat_session_id) ON DELETE CASCADE,
    ai_generation_request_id BIGINT REFERENCES ai_generation_requests(ai_generation_request_id) ON DELETE SET NULL,
    role                     VARCHAR(20) NOT NULL,
    content                  TEXT NOT NULL,
    source_metadata          JSONB,
    sequence_number          INTEGER NOT NULL CHECK (sequence_number > 0),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_chat_messages_sequence UNIQUE (ai_chat_session_id, sequence_number),
    CONSTRAINT ck_ai_chat_messages_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'))
);
CREATE INDEX idx_ai_chat_messages_request ON ai_chat_messages(ai_generation_request_id);

CREATE TABLE recommendation_sessions (
    recommendation_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    trip_id                    BIGINT REFERENCES trips(trip_id) ON DELETE CASCADE,
    ai_generation_request_id   BIGINT REFERENCES ai_generation_requests(ai_generation_request_id) ON DELETE SET NULL,
    source                     VARCHAR(20) NOT NULL DEFAULT 'RULE',
    status                     VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    requested_count            SMALLINT NOT NULL CHECK (requested_count > 0),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                 TIMESTAMPTZ,
    CONSTRAINT ck_recommendation_sessions_source CHECK (source IN ('RULE', 'AI', 'RAG', 'HYBRID')),
    CONSTRAINT ck_recommendation_sessions_status CHECK (status IN ('CREATED', 'SERVED', 'EXPIRED', 'FAILED')),
    CONSTRAINT ck_recommendation_sessions_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
);
CREATE INDEX idx_recommendation_sessions_user_time ON recommendation_sessions(user_id, created_at DESC);
CREATE INDEX idx_recommendation_sessions_trip ON recommendation_sessions(trip_id, created_at DESC);

CREATE TABLE recommendation_results (
    recommendation_result_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_session_id BIGINT NOT NULL REFERENCES recommendation_sessions(recommendation_session_id) ON DELETE CASCADE,
    place_id                   BIGINT NOT NULL REFERENCES places(place_id),
    rank                       SMALLINT NOT NULL CHECK (rank > 0),
    score                      NUMERIC(8,6) NOT NULL CHECK (score BETWEEN 0 AND 1),
    reason                     VARCHAR(1000),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_recommendation_results_place UNIQUE (recommendation_session_id, place_id),
    CONSTRAINT uk_recommendation_results_rank UNIQUE (recommendation_session_id, rank)
);
CREATE INDEX idx_recommendation_results_place ON recommendation_results(place_id, created_at DESC);

CREATE TABLE recommendation_events (
    recommendation_event_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    recommendation_result_id BIGINT NOT NULL REFERENCES recommendation_results(recommendation_result_id) ON DELETE CASCADE,
    event_type               VARCHAR(30) NOT NULL,
    metadata                 JSONB,
    occurred_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recommendation_events_type CHECK (event_type IN ('IMPRESSION', 'CLICK', 'FAVORITE', 'ADD_TO_TRIP', 'REMOVE_FROM_TRIP', 'DISMISS'))
);
CREATE INDEX idx_recommendation_events_user_type_time ON recommendation_events(user_id, event_type, occurred_at DESC);
CREATE INDEX idx_recommendation_events_result_time ON recommendation_events(recommendation_result_id, occurred_at DESC);

COMMENT ON TABLE ai_chat_sessions IS 'Conversation units for the AI guide screen';
COMMENT ON TABLE ai_generation_requests IS 'AI itinerary, recommendation, optimization, and chat request history';
COMMENT ON TABLE ai_chat_messages IS 'Ordered messages belonging to an AI guide conversation';
COMMENT ON TABLE recommendation_sessions IS 'Normalized recommendation request context';
COMMENT ON TABLE recommendation_results IS 'Ranked place results shown on the recommendation screen';
COMMENT ON TABLE recommendation_events IS 'User behavior events tied to an actual recommendation result';
