-- All My Trips Flyway migration: V4__travel_record
-- Target: PostgreSQL 16+

CREATE TABLE travel_records (
    travel_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id          BIGINT NOT NULL REFERENCES trips(trip_id),
    user_id          BIGINT NOT NULL REFERENCES users(user_id),
    title            VARCHAR(200) NOT NULL,
    content          TEXT NOT NULL,
    rating           SMALLINT CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    visibility       VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT uk_travel_records_trip UNIQUE (trip_id),
    CONSTRAINT uk_travel_records_trip_user UNIQUE (trip_id, user_id),
    CONSTRAINT ck_travel_records_visibility CHECK (visibility IN ('PRIVATE', 'PUBLIC'))
);
CREATE INDEX idx_travel_records_user_created ON travel_records(user_id, created_at DESC);
CREATE INDEX idx_travel_records_visibility_created ON travel_records(visibility, created_at DESC);
CREATE TRIGGER trg_travel_records_updated_at BEFORE UPDATE ON travel_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_record_images (
    travel_record_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id       BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    image_url              VARCHAR(1000) NOT NULL,
    alt_text               VARCHAR(255),
    sort_order             INTEGER NOT NULL DEFAULT 1 CHECK (sort_order > 0),
    is_cover               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_travel_record_images_order UNIQUE (travel_record_id, sort_order)
);
CREATE UNIQUE INDEX uk_travel_record_images_one_cover ON travel_record_images(travel_record_id) WHERE is_cover;

COMMENT ON TABLE travel_records IS 'Travel reviews for completed trips';
COMMENT ON TABLE travel_record_images IS 'Images attached to travel records';
