-- All My Trips Flyway migration: V5__travel_record_social
-- Target: PostgreSQL 16+

CREATE TABLE travel_record_comments (
    travel_record_comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id         BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    user_id                  BIGINT NOT NULL REFERENCES users(user_id),
    parent_comment_id        BIGINT REFERENCES travel_record_comments(travel_record_comment_id) ON DELETE CASCADE,
    content                  VARCHAR(2000) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMPTZ
);
CREATE INDEX idx_record_comments_record_created ON travel_record_comments(travel_record_id, created_at);
CREATE INDEX idx_record_comments_parent ON travel_record_comments(parent_comment_id);
CREATE TRIGGER trg_travel_record_comments_updated_at BEFORE UPDATE ON travel_record_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_record_likes (
    travel_record_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id      BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    user_id               BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_travel_record_likes UNIQUE (travel_record_id, user_id)
);
CREATE INDEX idx_record_likes_user_created ON travel_record_likes(user_id, created_at DESC);

CREATE TABLE travel_record_shares (
    travel_record_share_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id       BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    user_id                BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    channel                VARCHAR(20) NOT NULL,
    shared_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_travel_record_shares_channel CHECK (channel IN ('LINK', 'KAKAO', 'EMAIL', 'OTHER'))
);
CREATE INDEX idx_record_shares_record_time ON travel_record_shares(travel_record_id, shared_at DESC);

CREATE TABLE travel_record_reports (
    travel_record_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id        BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    reporter_user_id        BIGINT NOT NULL REFERENCES users(user_id),
    reason                  VARCHAR(30) NOT NULL,
    detail                  VARCHAR(1000),
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    processed_by            BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    processed_at            TIMESTAMPTZ,
    resolution_note         VARCHAR(1000),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_record_reports_reason CHECK (reason IN ('SPAM', 'ABUSE', 'INAPPROPRIATE', 'COPYRIGHT', 'PRIVACY', 'OTHER')),
    CONSTRAINT ck_record_reports_status CHECK (status IN ('PENDING', 'REVIEWING', 'RESOLVED', 'REJECTED'))
);
CREATE INDEX idx_record_reports_status_created ON travel_record_reports(status, created_at);
CREATE INDEX idx_record_reports_record_status ON travel_record_reports(travel_record_id, status);
CREATE UNIQUE INDEX uk_record_reports_open_report
    ON travel_record_reports(travel_record_id, reporter_user_id)
    WHERE status IN ('PENDING', 'REVIEWING');

COMMENT ON TABLE travel_record_comments IS 'Comments and replies on travel records';
COMMENT ON TABLE travel_record_likes IS 'User likes on travel records';
COMMENT ON TABLE travel_record_shares IS 'Accumulated travel record share events';
COMMENT ON TABLE travel_record_reports IS 'Travel record reports and administrator resolutions';
