-- All My Trips Flyway migration: V6__admin_operation
-- Target: PostgreSQL 16+

CREATE TABLE travel_themes (
    travel_theme_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(150) NOT NULL,
    description       VARCHAR(1000),
    country_code      CHAR(2),
    representative_region VARCHAR(100),
    duration_days     SMALLINT CHECK (duration_days IS NULL OR duration_days > 0),
    min_budget        NUMERIC(15,2) CHECK (min_budget IS NULL OR min_budget >= 0),
    max_budget        NUMERIC(15,2) CHECK (max_budget IS NULL OR max_budget >= 0),
    currency_code     CHAR(3) NOT NULL DEFAULT 'KRW',
    image_url         VARCHAR(1000),
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by        BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_travel_themes_budget CHECK (max_budget IS NULL OR min_budget IS NULL OR max_budget >= min_budget),
    CONSTRAINT ck_travel_themes_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);
CREATE INDEX idx_travel_themes_status_region ON travel_themes(status, representative_region);
CREATE TRIGGER trg_travel_themes_updated_at BEFORE UPDATE ON travel_themes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_theme_styles (
    travel_theme_id BIGINT NOT NULL REFERENCES travel_themes(travel_theme_id) ON DELETE CASCADE,
    travel_style_id SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (travel_theme_id, travel_style_id)
);

COMMENT ON TABLE travel_theme_styles IS 'Travel style tags shown on curated theme cards';

CREATE TABLE travel_theme_places (
    travel_theme_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_theme_id       BIGINT NOT NULL REFERENCES travel_themes(travel_theme_id) ON DELETE CASCADE,
    place_id              BIGINT NOT NULL REFERENCES places(place_id),
    day_number            SMALLINT CHECK (day_number IS NULL OR day_number > 0),
    sort_order            SMALLINT NOT NULL CHECK (sort_order > 0),
    recommendation_note   VARCHAR(500),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_travel_theme_places_place UNIQUE (travel_theme_id, place_id),
    CONSTRAINT uk_travel_theme_places_order UNIQUE (travel_theme_id, sort_order)
);

CREATE TABLE place_sync_jobs (
    place_sync_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    provider          VARCHAR(30) NOT NULL,
    job_type          VARCHAR(20) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_count   INTEGER NOT NULL DEFAULT 0 CHECK (requested_count >= 0),
    processed_count   INTEGER NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    created_count     INTEGER NOT NULL DEFAULT 0 CHECK (created_count >= 0),
    updated_count     INTEGER NOT NULL DEFAULT 0 CHECK (updated_count >= 0),
    failed_count      INTEGER NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
    error_summary     VARCHAR(1000),
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_place_sync_jobs_type CHECK (job_type IN ('FULL', 'INCREMENTAL', 'MANUAL')),
    CONSTRAINT ck_place_sync_jobs_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL_FAILED', 'FAILED')),
    CONSTRAINT ck_place_sync_jobs_counts CHECK (processed_count <= requested_count AND created_count + updated_count + failed_count <= processed_count),
    CONSTRAINT ck_place_sync_jobs_period CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);
CREATE INDEX idx_place_sync_jobs_status_created ON place_sync_jobs(status, created_at DESC);
CREATE INDEX idx_place_sync_jobs_provider_created ON place_sync_jobs(provider, created_at DESC);

CREATE TABLE place_sync_errors (
    place_sync_error_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_sync_job_id   BIGINT NOT NULL REFERENCES place_sync_jobs(place_sync_job_id) ON DELETE CASCADE,
    external_place_id   VARCHAR(100),
    error_code          VARCHAR(100),
    error_message       VARCHAR(1000) NOT NULL,
    raw_payload         JSONB,
    retry_status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count         SMALLINT NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    last_retried_at     TIMESTAMPTZ,
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_place_sync_errors_retry_status CHECK (retry_status IN ('PENDING', 'RETRIED', 'RESOLVED', 'IGNORED'))
);
CREATE INDEX idx_place_sync_errors_job_status ON place_sync_errors(place_sync_job_id, retry_status);

CREATE TABLE admin_audit_logs (
    admin_audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    action_type        VARCHAR(30) NOT NULL,
    target_type        VARCHAR(50) NOT NULL,
    target_id          VARCHAR(100),
    before_data        JSONB,
    after_data         JSONB,
    request_id         VARCHAR(100),
    ip_address         INET,
    user_agent         VARCHAR(500),
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_admin_audit_logs_admin_time ON admin_audit_logs(admin_user_id, occurred_at DESC);
CREATE INDEX idx_admin_audit_logs_target ON admin_audit_logs(target_type, target_id, occurred_at DESC);
CREATE INDEX idx_admin_audit_logs_request ON admin_audit_logs(request_id);

COMMENT ON TABLE travel_themes IS 'Curated theme cards registered from the administrator screen';
COMMENT ON TABLE travel_theme_places IS 'Ordered places composing a curated travel theme';
COMMENT ON TABLE place_sync_jobs IS 'External place synchronization job history';
COMMENT ON TABLE place_sync_errors IS 'Record-level failures from place synchronization jobs';
COMMENT ON TABLE admin_audit_logs IS 'Immutable administrator and system action audit trail';
