-- All My Trips Flyway migration: V7__ticket_reservation
-- Target: PostgreSQL 16+

CREATE TABLE ticket_products (
    ticket_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id          BIGINT NOT NULL REFERENCES places(place_id),
    name              VARCHAR(150) NOT NULL,
    description       TEXT,
    sale_start_at     TIMESTAMPTZ NOT NULL,
    sale_end_at       TIMESTAMPTZ NOT NULL,
    usage_start_date  DATE NOT NULL,
    usage_end_date    DATE NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_products_sale_period CHECK (sale_end_at > sale_start_at),
    CONSTRAINT ck_ticket_products_usage_period CHECK (usage_end_date >= usage_start_date),
    CONSTRAINT ck_ticket_products_status CHECK (status IN ('DRAFT', 'ON_SALE', 'SOLD_OUT', 'ENDED', 'CANCELLED'))
);
CREATE INDEX idx_ticket_products_place_status ON ticket_products(place_id, status);
CREATE INDEX idx_ticket_products_sale_period ON ticket_products(sale_start_at, sale_end_at);
CREATE TRIGGER trg_ticket_products_updated_at BEFORE UPDATE ON ticket_products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_product_options (
    ticket_product_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_product_id        BIGINT NOT NULL REFERENCES ticket_products(ticket_product_id) ON DELETE CASCADE,
    name                     VARCHAR(150) NOT NULL,
    description              VARCHAR(1000),
    unit_price               NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    currency_code            CHAR(3) NOT NULL DEFAULT 'KRW',
    max_quantity_per_user    SMALLINT NOT NULL DEFAULT 4 CHECK (max_quantity_per_user > 0),
    sort_order               SMALLINT NOT NULL DEFAULT 1 CHECK (sort_order > 0),
    is_active                BOOLEAN NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ticket_product_options_name UNIQUE (ticket_product_id, name),
    CONSTRAINT uk_ticket_product_options_order UNIQUE (ticket_product_id, sort_order)
);
CREATE TRIGGER trg_ticket_product_options_updated_at BEFORE UPDATE ON ticket_product_options
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_time_slots (
    ticket_time_slot_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_product_option_id  BIGINT NOT NULL REFERENCES ticket_product_options(ticket_product_option_id) ON DELETE CASCADE,
    usage_date                DATE NOT NULL,
    start_time                TIME,
    end_time                  TIME,
    status                    VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ticket_time_slots UNIQUE NULLS NOT DISTINCT (ticket_product_option_id, usage_date, start_time),
    CONSTRAINT ck_ticket_time_slots_period CHECK (end_time IS NULL OR start_time IS NULL OR end_time > start_time),
    CONSTRAINT ck_ticket_time_slots_status CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);
CREATE INDEX idx_ticket_time_slots_date_status ON ticket_time_slots(usage_date, status);
CREATE TRIGGER trg_ticket_time_slots_updated_at BEFORE UPDATE ON ticket_time_slots
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_inventory (
    ticket_time_slot_id BIGINT PRIMARY KEY REFERENCES ticket_time_slots(ticket_time_slot_id) ON DELETE CASCADE,
    total_quantity      INTEGER NOT NULL CHECK (total_quantity >= 0),
    reserved_quantity   INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    version             BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_inventory_quantities CHECK (reserved_quantity <= total_quantity)
);
CREATE TRIGGER trg_ticket_inventory_updated_at BEFORE UPDATE ON ticket_inventory
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE reservations (
    reservation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_number VARCHAR(30) NOT NULL UNIQUE,
    user_id            BIGINT NOT NULL REFERENCES users(user_id),
    status             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_amount       NUMERIC(15,2) NOT NULL CHECK (total_amount >= 0),
    currency_code      CHAR(3) NOT NULL DEFAULT 'KRW',
    expires_at         TIMESTAMPTZ,
    confirmed_at       TIMESTAMPTZ,
    cancelled_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'USED'))
);
CREATE INDEX idx_reservations_user_status_created ON reservations(user_id, status, created_at DESC);
CREATE INDEX idx_reservations_status_expires ON reservations(status, expires_at);
CREATE TRIGGER trg_reservations_updated_at BEFORE UPDATE ON reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE reservation_items (
    reservation_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      BIGINT NOT NULL REFERENCES reservations(reservation_id) ON DELETE CASCADE,
    ticket_time_slot_id BIGINT NOT NULL REFERENCES ticket_time_slots(ticket_time_slot_id),
    product_name        VARCHAR(150) NOT NULL,
    option_name         VARCHAR(150) NOT NULL,
    usage_date          DATE NOT NULL,
    usage_start_time    TIME,
    quantity            SMALLINT NOT NULL CHECK (quantity > 0),
    unit_price          NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    line_amount         NUMERIC(15,2) NOT NULL CHECK (line_amount >= 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reservation_items_slot UNIQUE (reservation_id, ticket_time_slot_id),
    CONSTRAINT ck_reservation_items_line_amount CHECK (line_amount = unit_price * quantity)
);
CREATE INDEX idx_reservation_items_slot ON reservation_items(ticket_time_slot_id);

CREATE TABLE payments (
    payment_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id       BIGINT NOT NULL REFERENCES reservations(reservation_id),
    idempotency_key      VARCHAR(100) NOT NULL UNIQUE,
    provider             VARCHAR(30) NOT NULL,
    provider_payment_key VARCHAR(100),
    method               VARCHAR(20) NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'READY',
    amount               NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
    currency_code        CHAR(3) NOT NULL DEFAULT 'KRW',
    failure_code         VARCHAR(50),
    failure_message      VARCHAR(500),
    requested_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at          TIMESTAMPTZ,
    cancelled_at         TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payments_provider_key UNIQUE (provider, provider_payment_key),
    CONSTRAINT ck_payments_method CHECK (method IN ('CARD', 'TRANSFER', 'VIRTUAL_ACCOUNT', 'EASY_PAY')),
    CONSTRAINT ck_payments_status CHECK (status IN ('READY', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED'))
);
CREATE INDEX idx_payments_reservation_status ON payments(reservation_id, status);
CREATE TRIGGER trg_payments_updated_at BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE issued_tickets (
    issued_ticket_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_item_id     BIGINT NOT NULL REFERENCES reservation_items(reservation_item_id),
    ticket_number           VARCHAR(50) NOT NULL UNIQUE,
    verification_token_hash CHAR(64) NOT NULL UNIQUE,
    issue_method            VARCHAR(20) NOT NULL DEFAULT 'MOBILE',
    status                  VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
    valid_from              TIMESTAMPTZ NOT NULL,
    valid_until             TIMESTAMPTZ NOT NULL,
    issued_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at                 TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    replaced_by_ticket_id   BIGINT UNIQUE REFERENCES issued_tickets(issued_ticket_id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_issued_tickets_method CHECK (issue_method IN ('MOBILE', 'EMAIL', 'PRINT', 'ONSITE')),
    CONSTRAINT ck_issued_tickets_status CHECK (status IN ('ISSUED', 'USED', 'CANCELLED', 'EXPIRED', 'REPLACED')),
    CONSTRAINT ck_issued_tickets_validity CHECK (valid_until > valid_from),
    CONSTRAINT ck_issued_tickets_used_at CHECK (used_at IS NULL OR used_at >= issued_at),
    CONSTRAINT ck_issued_tickets_cancelled_at CHECK (cancelled_at IS NULL OR cancelled_at >= issued_at)
);
CREATE INDEX idx_issued_tickets_item ON issued_tickets(reservation_item_id);
CREATE INDEX idx_issued_tickets_status_valid_until ON issued_tickets(status, valid_until);
CREATE TRIGGER trg_issued_tickets_updated_at BEFORE UPDATE ON issued_tickets
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_validation_logs (
    ticket_validation_log_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issued_ticket_id           BIGINT REFERENCES issued_tickets(issued_ticket_id),
    validator_user_id          BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    presented_token_fingerprint CHAR(64),
    validation_result          VARCHAR(20) NOT NULL,
    validation_channel         VARCHAR(20) NOT NULL DEFAULT 'ADMIN_WEB',
    device_id                  VARCHAR(100),
    failure_reason             VARCHAR(500),
    metadata                   JSONB,
    validated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_validation_logs_result CHECK (validation_result IN ('SUCCESS', 'NOT_FOUND', 'ALREADY_USED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_ticket_validation_logs_channel CHECK (validation_channel IN ('ADMIN_WEB', 'MOCK_SCANNER', 'API'))
);
CREATE INDEX idx_ticket_validation_logs_ticket_time ON ticket_validation_logs(issued_ticket_id, validated_at DESC);
CREATE INDEX idx_ticket_validation_logs_validator_time ON ticket_validation_logs(validator_user_id, validated_at DESC);
CREATE INDEX idx_ticket_validation_logs_result_time ON ticket_validation_logs(validation_result, validated_at DESC);
CREATE INDEX idx_ticket_validation_logs_fingerprint ON ticket_validation_logs(presented_token_fingerprint);

COMMENT ON TABLE ticket_products IS 'Reservable attraction, festival, and activity ticket groups';
COMMENT ON TABLE ticket_product_options IS 'Selectable price options shown on the ticket detail screen';
COMMENT ON TABLE ticket_time_slots IS 'Bookable usage dates and times for a ticket option';
COMMENT ON TABLE ticket_inventory IS 'Per-time-slot inventory aggregate for concurrency control';
COMMENT ON TABLE reservations IS 'Mock ticket reservation orders';
COMMENT ON TABLE reservation_items IS 'Reservation line item snapshots';
COMMENT ON TABLE payments IS 'Idempotent mock payment attempts and results';
COMMENT ON TABLE issued_tickets IS 'Individually issued mock electronic tickets';
COMMENT ON TABLE ticket_validation_logs IS 'Mock QR and barcode ticket validation attempts';
