-- All My Trips Flyway migration: V9__flight_booking
-- Target: PostgreSQL 16+
--
-- 우리는 항공권을 팔지 않는다. 결제는 항공사·여행사 페이지에서 일어나므로
-- "예약 완료" 상태를 저장할 방법이 없다. 그래서 booking_status 컬럼을 만들지 않고
-- user_reported_booked(자가 신고) + booking_ref(예약번호)에서 상태를 파생한다.

CREATE TABLE flight_bookings (
    flight_booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id               BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    user_id               BIGINT NOT NULL REFERENCES users(user_id),
    leg                   SMALLINT NOT NULL,
    offer_id              VARCHAR(64) NOT NULL,
    provider              VARCHAR(32) NOT NULL,

    -- 운임 스냅샷. 표시 운임은 실시간으로 바뀌므로 이탈 시점 값을 박제한다.
    -- 재검색해도 이 값은 덮어쓰지 않는다. 어디에도 "결제 금액"으로 표시하지 않는다.
    carrier_code          VARCHAR(3) NOT NULL,
    -- 항공사 한글명도 스냅샷에 넣는다. 조회 시점에 코드→이름 매핑 테이블을 다시 태우면
    -- 매핑이 바뀌었을 때 과거 예약의 표기가 따라 바뀐다.
    carrier_name          VARCHAR(60) NOT NULL,
    flight_number         VARCHAR(10) NOT NULL,
    departure_at          TIMESTAMPTZ NOT NULL,
    arrival_at            TIMESTAMPTZ NOT NULL,
    -- TAGO가 운임을 모르는 편에 0을 준다. 그런 편은 값 없이 출처만 UNAVAILABLE로 남긴다.
    quoted_total_price    NUMERIC(12,2) CHECK (quoted_total_price >= 0),
    quoted_currency       CHAR(3) NOT NULL DEFAULT 'KRW',
    -- 이때 본 값이 공시운임이었는지 실판매가였는지 못 밝히면 CS 대응이 불가능해진다.
    quoted_price_source   VARCHAR(16) NOT NULL,
    quoted_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 사용자가 "예약했다"고 직접 표시한 값. 결제 확인이 아니다.
    user_reported_booked  BOOLEAN NOT NULL DEFAULT FALSE,
    user_reported_at      TIMESTAMPTZ,

    -- 예약번호가 들어오면 확정으로 승격한다.
    booking_ref           VARCHAR(32),
    booking_ref_added_at  TIMESTAMPTZ,

    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_flight_bookings_trip_leg UNIQUE (trip_id, leg),
    CONSTRAINT ck_flight_bookings_leg CHECK (leg IN (0, 1)),
    CONSTRAINT ck_flight_bookings_arrival CHECK (arrival_at >= departure_at),
    CONSTRAINT ck_flight_bookings_price_source
        CHECK (quoted_price_source IN ('PUBLISHED', 'MARKET', 'UNAVAILABLE', 'MOCK')),
    CONSTRAINT ck_flight_bookings_price_presence
        CHECK (quoted_total_price IS NOT NULL OR quoted_price_source = 'UNAVAILABLE')
);
CREATE INDEX idx_flight_bookings_user ON flight_bookings(user_id, trip_id);
CREATE TRIGGER trg_flight_bookings_updated_at BEFORE UPDATE ON flight_bookings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 외부 사이트로 나간 이력.
-- 복귀 감지(visibilitychange)는 놓칠 수 있으므로, 놓친 건을 다음 방문에 다시 물어보려면
-- 이 로그가 있어야 한다. 나중에 제휴 커미션 대조에도 쓴다.
CREATE TABLE flight_outbound_clicks (
    flight_outbound_click_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(user_id),
    trip_id      BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    leg          SMALLINT NOT NULL,
    offer_id     VARCHAR(64) NOT NULL,
    provider     VARCHAR(32) NOT NULL,
    deeplink_url TEXT NOT NULL,
    clicked_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- visibilitychange 감지 시각. 알림 확인·앱 전환에도 발생하므로 부정확할 수 있다.
    returned_at  TIMESTAMPTZ,
    outcome      VARCHAR(16),

    CONSTRAINT ck_flight_outbound_clicks_leg CHECK (leg IN (0, 1)),
    CONSTRAINT ck_flight_outbound_clicks_outcome
        CHECK (outcome IS NULL OR outcome IN ('REPORTED_YES', 'REPORTED_NO', 'LATER', 'NO_RESPONSE'))
);
CREATE INDEX idx_flight_outbound_clicks_trip_leg
    ON flight_outbound_clicks(trip_id, leg, clicked_at DESC);
-- 무응답 재질문 배너가 이 인덱스로 조회한다.
CREATE INDEX idx_flight_outbound_clicks_pending
    ON flight_outbound_clicks(user_id, outcome);

-- IATA ↔ TAGO 공항 코드 매핑은 테이블 대신 DomesticAirport enum으로 고정했다.
-- 국내 공항이 15개뿐이고 바뀌지 않아서, 테이블로 두면 provider가 조회 계층에 의존하게 되고
-- 단위 테스트에 DB가 필요해진다. 원본은 GetArprtList 응답이다.
