-- All My Trips integrated schema
-- Target: PostgreSQL 16+ / UTF-8
-- Prerequisite: database/init/create_extensions.sql must be run by a DB owner.

-- =========================================================
-- V1__member_and_place.sql
-- =========================================================

-- All My Trips Flyway migration: V1__member_and_place
-- Target: PostgreSQL 16+ / UTF-8

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END;
$$;

CREATE TABLE users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          CITEXT NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    nickname       VARCHAR(50) NOT NULL UNIQUE,
    role           VARCHAR(20) NOT NULL DEFAULT 'USER',
    status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_styles (
    travel_style_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(30) NOT NULL UNIQUE,
    name             VARCHAR(50) NOT NULL UNIQUE,
    description      VARCHAR(500),
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order       SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_travel_styles_updated_at BEFORE UPDATE ON travel_styles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_preferences (
    user_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    travel_style_id     SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    preference_score    SMALLINT NOT NULL DEFAULT 50 CHECK (preference_score BETWEEN 0 AND 100),
    source              VARCHAR(20) NOT NULL DEFAULT 'EXPLICIT',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_preferences_user_style UNIQUE (user_id, travel_style_id),
    CONSTRAINT ck_user_preferences_source CHECK (source IN ('EXPLICIT', 'INFERRED'))
);
CREATE INDEX idx_user_preferences_style_score ON user_preferences(travel_style_id, preference_score DESC);
CREATE TRIGGER trg_user_preferences_updated_at BEFORE UPDATE ON user_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE places (
    place_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_provider  VARCHAR(30),
    external_place_id  VARCHAR(100),
    category           VARCHAR(30) NOT NULL,
    name               VARCHAR(150) NOT NULL,
    country_code       CHAR(2) NOT NULL,
    region             VARCHAR(100),
    city               VARCHAR(100),
    address            VARCHAR(255),
    latitude           NUMERIC(10,7),
    longitude          NUMERIC(10,7),
    description        TEXT,
    phone              VARCHAR(50),
    website_url        VARCHAR(500),
    average_rating     NUMERIC(3,2),
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_places_external UNIQUE (external_provider, external_place_id),
    CONSTRAINT ck_places_category CHECK (category IN ('ATTRACTION', 'RESTAURANT', 'CAFE', 'ACCOMMODATION', 'FESTIVAL', 'ACTIVITY', 'TRANSPORT')),
    CONSTRAINT ck_places_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_places_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_places_rating CHECK (average_rating IS NULL OR average_rating BETWEEN 0 AND 5),
    CONSTRAINT ck_places_external_pair CHECK ((external_provider IS NULL) = (external_place_id IS NULL))
);
CREATE INDEX idx_places_search ON places(country_code, region, city, category, is_active);
CREATE INDEX idx_places_name ON places(name);
CREATE TRIGGER trg_places_updated_at BEFORE UPDATE ON places
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE place_images (
    place_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id       BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    image_url      VARCHAR(1000) NOT NULL,
    alt_text       VARCHAR(255),
    sort_order     SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    is_primary     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_images_order UNIQUE (place_id, sort_order)
);
CREATE UNIQUE INDEX uk_place_images_one_primary ON place_images(place_id) WHERE is_primary;

CREATE TABLE place_travel_styles (
    place_travel_style_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id              BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    travel_style_id       SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    relevance_score       SMALLINT NOT NULL CHECK (relevance_score BETWEEN 0 AND 100),
    source                VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_travel_styles UNIQUE (place_id, travel_style_id),
    CONSTRAINT ck_place_travel_styles_source CHECK (source IN ('MANUAL', 'AI', 'IMPORT'))
);
CREATE INDEX idx_place_travel_styles_rank ON place_travel_styles(travel_style_id, relevance_score DESC);
CREATE TRIGGER trg_place_travel_styles_updated_at BEFORE UPDATE ON place_travel_styles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    place_id    BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    memo        VARCHAR(500),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorites_user_place UNIQUE (user_id, place_id)
);
CREATE INDEX idx_favorites_user_created ON favorites(user_id, created_at DESC);

COMMENT ON TABLE users IS 'Member accounts';
COMMENT ON TABLE travel_styles IS 'Travel style code dictionary';
COMMENT ON TABLE user_preferences IS 'Per-user travel style preferences';
COMMENT ON TABLE places IS 'Searchable travel places';
COMMENT ON TABLE place_images IS 'Place image metadata';
COMMENT ON TABLE place_travel_styles IS 'Travel style relevance tags for places';
COMMENT ON TABLE favorites IS 'Places saved by users';

CREATE TABLE place_reviews (
    place_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id        BIGINT NOT NULL REFERENCES places(place_id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    rating          SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content         VARCHAR(1000) NOT NULL,
    verified_visit  BOOLEAN NOT NULL DEFAULT FALSE,
    status          VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_reviews_user_place UNIQUE (place_id, user_id),
    CONSTRAINT ck_place_reviews_status CHECK (status IN ('VISIBLE', 'HIDDEN'))
);
CREATE INDEX idx_place_reviews_place_created
    ON place_reviews(place_id, created_at DESC, place_review_id DESC)
    WHERE status = 'VISIBLE';
CREATE TRIGGER trg_place_reviews_updated_at BEFORE UPDATE ON place_reviews
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
COMMENT ON TABLE place_reviews IS 'User ratings and reviews for individual places';


-- =========================================================
-- V2__trip_and_itinerary.sql
-- =========================================================

-- All My Trips Flyway migration: V2__trip_and_itinerary
-- Target: PostgreSQL 16+

CREATE TABLE trips (
    trip_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users(user_id),
    title                 VARCHAR(150) NOT NULL,
    destination_name      VARCHAR(150) NOT NULL,
    start_date             DATE NOT NULL,
    end_date               DATE NOT NULL,
    companion_type        VARCHAR(20) NOT NULL,
    companion_count       SMALLINT NOT NULL DEFAULT 1 CHECK (companion_count > 0),
    purpose                VARCHAR(500),
    budget_amount          NUMERIC(15,2) CHECK (budget_amount IS NULL OR budget_amount >= 0),
    currency_code          CHAR(3) NOT NULL DEFAULT 'KRW',
    transport_preference   VARCHAR(100),
    food_preference        VARCHAR(255),
    pace                   VARCHAR(20),
    accommodation_style    VARCHAR(100),
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    source                 VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    booking_confirmed_at   TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at             TIMESTAMPTZ,
    CONSTRAINT ck_trips_period CHECK (end_date >= start_date),
    CONSTRAINT ck_trips_companion CHECK (companion_type IN ('SOLO', 'FRIENDS', 'COUPLE', 'FAMILY', 'GROUP', 'OTHER')),
    CONSTRAINT ck_trips_pace CHECK (pace IS NULL OR pace IN ('RELAXED', 'NORMAL', 'PACKED')),
    CONSTRAINT ck_trips_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_trips_source CHECK (source IN ('MANUAL', 'AI'))
);
CREATE INDEX idx_trips_user_status_dates ON trips(user_id, status, start_date, end_date);
CREATE TRIGGER trg_trips_updated_at BEFORE UPDATE ON trips
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE trip_travel_styles (
    trip_id         BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    travel_style_id SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    priority        SMALLINT NOT NULL DEFAULT 1 CHECK (priority > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (trip_id, travel_style_id),
    CONSTRAINT uk_trip_travel_styles_priority UNIQUE (trip_id, priority)
);

CREATE TABLE trip_days (
    trip_day_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id     BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    day_number  SMALLINT NOT NULL CHECK (day_number > 0),
    trip_date   DATE NOT NULL,
    title       VARCHAR(150),
    memo        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_trip_days_number UNIQUE (trip_id, day_number),
    CONSTRAINT uk_trip_days_date UNIQUE (trip_id, trip_date)
);
CREATE TRIGGER trg_trip_days_updated_at BEFORE UPDATE ON trip_days
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE itinerary_items (
    itinerary_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_day_id       BIGINT NOT NULL REFERENCES trip_days(trip_day_id) ON DELETE CASCADE,
    place_id          BIGINT REFERENCES places(place_id) ON DELETE SET NULL,
    item_type         VARCHAR(30) NOT NULL,
    title             VARCHAR(150) NOT NULL,
    start_time        TIME,
    end_time          TIME,
    sort_order        SMALLINT NOT NULL CHECK (sort_order >= 0),
    memo              TEXT,
    estimated_cost    NUMERIC(15,2) CHECK (estimated_cost IS NULL OR estimated_cost >= 0),
    currency_code     CHAR(3) NOT NULL DEFAULT 'KRW',
    source            VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_itinerary_items_order UNIQUE (trip_day_id, sort_order),
    CONSTRAINT ck_itinerary_items_type CHECK (item_type IN ('PLACE', 'MEAL', 'ACCOMMODATION', 'TRANSPORT', 'ACTIVITY', 'NOTE')),
    CONSTRAINT ck_itinerary_items_period CHECK (end_time IS NULL OR start_time IS NULL OR end_time >= start_time),
    CONSTRAINT ck_itinerary_items_source CHECK (source IN ('MANUAL', 'AI'))
);
CREATE INDEX idx_itinerary_items_place ON itinerary_items(place_id);
CREATE TRIGGER trg_itinerary_items_updated_at BEFORE UPDATE ON itinerary_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE trip_share_links (
    trip_share_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT NOT NULL REFERENCES trips(trip_id) ON DELETE CASCADE,
    created_by         BIGINT NOT NULL REFERENCES users(user_id),
    token_hash         CHAR(64) NOT NULL UNIQUE,
    permission         VARCHAR(20) NOT NULL DEFAULT 'VIEW',
    expires_at         TIMESTAMPTZ,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_share_links_permission CHECK (permission IN ('VIEW')),
    CONSTRAINT ck_trip_share_links_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
);
CREATE INDEX idx_trip_share_links_trip_active ON trip_share_links(trip_id, revoked_at, expires_at);

COMMENT ON TABLE trips IS 'User travel plans and input conditions';
COMMENT ON TABLE trip_travel_styles IS 'Travel styles selected for a trip';
COMMENT ON TABLE trip_days IS 'Daily sections of a trip';
COMMENT ON TABLE itinerary_items IS 'Ordered activities within a trip day';
COMMENT ON TABLE trip_share_links IS 'Revocable read-only links for the schedule share screen';


-- =========================================================
-- V3__ai_and_recommendation.sql
-- =========================================================

-- All My Trips Flyway migration: V3__ai_and_recommendation
-- Target: PostgreSQL 16+

CREATE TABLE ai_chat_sessions (
    ai_chat_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    trip_id            BIGINT REFERENCES trips(trip_id) ON DELETE SET NULL,
    title              VARCHAR(150),
    status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_at    TIMESTAMPTZ,
    CONSTRAINT ck_ai_chat_sessions_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);
CREATE INDEX idx_ai_chat_sessions_user_recent ON ai_chat_sessions(user_id, last_message_at DESC NULLS LAST);
CREATE TRIGGER trg_ai_chat_sessions_updated_at BEFORE UPDATE ON ai_chat_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ai_generation_requests (
    ai_generation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT NOT NULL REFERENCES users(user_id),
    trip_id                   BIGINT REFERENCES trips(trip_id) ON DELETE SET NULL,
    ai_chat_session_id        BIGINT REFERENCES ai_chat_sessions(ai_chat_session_id) ON DELETE SET NULL,
    request_type              VARCHAR(30) NOT NULL,
    provider                  VARCHAR(50) NOT NULL,
    model_name                VARCHAR(100) NOT NULL,
    prompt_version            VARCHAR(50) NOT NULL,
    input_payload             JSONB NOT NULL,
    output_payload            JSONB,
    status                    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    error_message             VARCHAR(1000),
    input_tokens              INTEGER CHECK (input_tokens IS NULL OR input_tokens >= 0),
    output_tokens             INTEGER CHECK (output_tokens IS NULL OR output_tokens >= 0),
    requested_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at              TIMESTAMPTZ,
    CONSTRAINT ck_ai_generation_requests_type CHECK (request_type IN ('CREATE_ITINERARY', 'RECOMMEND_PLACES', 'OPTIMIZE_ROUTE', 'CHAT')),
    CONSTRAINT ck_ai_generation_requests_status CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_ai_generation_requests_period CHECK (completed_at IS NULL OR completed_at >= requested_at)
);
CREATE INDEX idx_ai_generation_requests_user_time ON ai_generation_requests(user_id, requested_at DESC);
CREATE INDEX idx_ai_generation_requests_trip_type ON ai_generation_requests(trip_id, request_type);
CREATE INDEX idx_ai_generation_requests_status ON ai_generation_requests(status, requested_at);

CREATE TABLE ai_chat_messages (
    ai_chat_message_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_chat_session_id       BIGINT NOT NULL REFERENCES ai_chat_sessions(ai_chat_session_id) ON DELETE CASCADE,
    ai_generation_request_id BIGINT REFERENCES ai_generation_requests(ai_generation_request_id) ON DELETE SET NULL,
    role                     VARCHAR(20) NOT NULL,
    content                  TEXT NOT NULL,
    source_metadata          JSONB,
    sequence_number          INTEGER NOT NULL CHECK (sequence_number > 0),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_chat_messages_sequence UNIQUE (ai_chat_session_id, sequence_number),
    CONSTRAINT ck_ai_chat_messages_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'))
);
CREATE INDEX idx_ai_chat_messages_request ON ai_chat_messages(ai_generation_request_id);

CREATE TABLE recommendation_sessions (
    recommendation_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    trip_id                    BIGINT REFERENCES trips(trip_id) ON DELETE CASCADE,
    ai_generation_request_id   BIGINT REFERENCES ai_generation_requests(ai_generation_request_id) ON DELETE SET NULL,
    source                     VARCHAR(20) NOT NULL DEFAULT 'RULE',
    status                     VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    requested_count            SMALLINT NOT NULL CHECK (requested_count > 0),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                 TIMESTAMPTZ,
    CONSTRAINT ck_recommendation_sessions_source CHECK (source IN ('RULE', 'AI', 'RAG', 'HYBRID')),
    CONSTRAINT ck_recommendation_sessions_status CHECK (status IN ('CREATED', 'SERVED', 'EXPIRED', 'FAILED')),
    CONSTRAINT ck_recommendation_sessions_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
);
CREATE INDEX idx_recommendation_sessions_user_time ON recommendation_sessions(user_id, created_at DESC);
CREATE INDEX idx_recommendation_sessions_trip ON recommendation_sessions(trip_id, created_at DESC);

CREATE TABLE recommendation_results (
    recommendation_result_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_session_id BIGINT NOT NULL REFERENCES recommendation_sessions(recommendation_session_id) ON DELETE CASCADE,
    place_id                   BIGINT NOT NULL REFERENCES places(place_id),
    rank                       SMALLINT NOT NULL CHECK (rank > 0),
    score                      NUMERIC(8,6) NOT NULL CHECK (score BETWEEN 0 AND 1),
    reason                     VARCHAR(1000),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_recommendation_results_place UNIQUE (recommendation_session_id, place_id),
    CONSTRAINT uk_recommendation_results_rank UNIQUE (recommendation_session_id, rank)
);
CREATE INDEX idx_recommendation_results_place ON recommendation_results(place_id, created_at DESC);

CREATE TABLE recommendation_events (
    recommendation_event_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    recommendation_result_id BIGINT NOT NULL REFERENCES recommendation_results(recommendation_result_id) ON DELETE CASCADE,
    event_type               VARCHAR(30) NOT NULL,
    metadata                 JSONB,
    occurred_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recommendation_events_type CHECK (event_type IN ('IMPRESSION', 'CLICK', 'FAVORITE', 'ADD_TO_TRIP', 'REMOVE_FROM_TRIP', 'DISMISS'))
);
CREATE INDEX idx_recommendation_events_user_type_time ON recommendation_events(user_id, event_type, occurred_at DESC);
CREATE INDEX idx_recommendation_events_result_time ON recommendation_events(recommendation_result_id, occurred_at DESC);

COMMENT ON TABLE ai_chat_sessions IS 'Conversation units for the AI guide screen';
COMMENT ON TABLE ai_generation_requests IS 'AI itinerary, recommendation, optimization, and chat request history';
COMMENT ON TABLE ai_chat_messages IS 'Ordered messages belonging to an AI guide conversation';
COMMENT ON TABLE recommendation_sessions IS 'Normalized recommendation request context';
COMMENT ON TABLE recommendation_results IS 'Ranked place results shown on the recommendation screen';
COMMENT ON TABLE recommendation_events IS 'User behavior events tied to an actual recommendation result';


-- =========================================================
-- V4__travel_record.sql
-- =========================================================

-- All My Trips Flyway migration: V4__travel_record
-- Target: PostgreSQL 16+

CREATE TABLE travel_records (
    travel_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id          BIGINT NOT NULL REFERENCES trips(trip_id),
    user_id          BIGINT NOT NULL REFERENCES users(user_id),
    title            VARCHAR(200) NOT NULL,
    content          TEXT NOT NULL,
    rating           SMALLINT CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    visibility       VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT uk_travel_records_trip UNIQUE (trip_id),
    CONSTRAINT uk_travel_records_trip_user UNIQUE (trip_id, user_id),
    CONSTRAINT ck_travel_records_visibility CHECK (visibility IN ('PRIVATE', 'PUBLIC'))
);
CREATE INDEX idx_travel_records_user_created ON travel_records(user_id, created_at DESC);
CREATE INDEX idx_travel_records_visibility_created ON travel_records(visibility, created_at DESC);
CREATE TRIGGER trg_travel_records_updated_at BEFORE UPDATE ON travel_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_record_images (
    travel_record_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id       BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    image_url              VARCHAR(1000) NOT NULL,
    alt_text               VARCHAR(255),
    sort_order             INTEGER NOT NULL DEFAULT 1 CHECK (sort_order > 0),
    is_cover               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_travel_record_images_order UNIQUE (travel_record_id, sort_order)
);
CREATE UNIQUE INDEX uk_travel_record_images_one_cover ON travel_record_images(travel_record_id) WHERE is_cover;

COMMENT ON TABLE travel_records IS 'Travel reviews for completed trips';
COMMENT ON TABLE travel_record_images IS 'Images attached to travel records';


-- =========================================================
-- V5__travel_record_social.sql
-- =========================================================

-- All My Trips Flyway migration: V5__travel_record_social
-- Target: PostgreSQL 16+

CREATE TABLE travel_record_comments (
    travel_record_comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id         BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    user_id                  BIGINT NOT NULL REFERENCES users(user_id),
    parent_comment_id        BIGINT REFERENCES travel_record_comments(travel_record_comment_id) ON DELETE CASCADE,
    content                  VARCHAR(2000) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMPTZ
);
CREATE INDEX idx_record_comments_record_created ON travel_record_comments(travel_record_id, created_at);
CREATE INDEX idx_record_comments_parent ON travel_record_comments(parent_comment_id);
CREATE TRIGGER trg_travel_record_comments_updated_at BEFORE UPDATE ON travel_record_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_record_likes (
    travel_record_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id      BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    user_id               BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_travel_record_likes UNIQUE (travel_record_id, user_id)
);
CREATE INDEX idx_record_likes_user_created ON travel_record_likes(user_id, created_at DESC);

CREATE TABLE travel_record_shares (
    travel_record_share_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id       BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    user_id                BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    channel                VARCHAR(20) NOT NULL,
    shared_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_travel_record_shares_channel CHECK (channel IN ('LINK', 'KAKAO', 'EMAIL', 'OTHER'))
);
CREATE INDEX idx_record_shares_record_time ON travel_record_shares(travel_record_id, shared_at DESC);

CREATE TABLE travel_record_reports (
    travel_record_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_record_id        BIGINT NOT NULL REFERENCES travel_records(travel_record_id) ON DELETE CASCADE,
    reporter_user_id        BIGINT NOT NULL REFERENCES users(user_id),
    reason                  VARCHAR(30) NOT NULL,
    detail                  VARCHAR(1000),
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    processed_by            BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    processed_at            TIMESTAMPTZ,
    resolution_note         VARCHAR(1000),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_record_reports_reason CHECK (reason IN ('SPAM', 'ABUSE', 'INAPPROPRIATE', 'COPYRIGHT', 'PRIVACY', 'OTHER')),
    CONSTRAINT ck_record_reports_status CHECK (status IN ('PENDING', 'REVIEWING', 'RESOLVED', 'REJECTED'))
);
CREATE INDEX idx_record_reports_status_created ON travel_record_reports(status, created_at);
CREATE INDEX idx_record_reports_record_status ON travel_record_reports(travel_record_id, status);
CREATE UNIQUE INDEX uk_record_reports_open_report
    ON travel_record_reports(travel_record_id, reporter_user_id)
    WHERE status IN ('PENDING', 'REVIEWING');

COMMENT ON TABLE travel_record_comments IS 'Comments and replies on travel records';
COMMENT ON TABLE travel_record_likes IS 'User likes on travel records';
COMMENT ON TABLE travel_record_shares IS 'Accumulated travel record share events';
COMMENT ON TABLE travel_record_reports IS 'Travel record reports and administrator resolutions';


-- =========================================================
-- V6__admin_operation.sql
-- =========================================================

-- All My Trips Flyway migration: V6__admin_operation
-- Target: PostgreSQL 16+

CREATE TABLE travel_themes (
    travel_theme_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(150) NOT NULL,
    description       VARCHAR(1000),
    country_code      CHAR(2),
    representative_region VARCHAR(100),
    duration_days     SMALLINT CHECK (duration_days IS NULL OR duration_days > 0),
    min_budget        NUMERIC(15,2) CHECK (min_budget IS NULL OR min_budget >= 0),
    max_budget        NUMERIC(15,2) CHECK (max_budget IS NULL OR max_budget >= 0),
    currency_code     CHAR(3) NOT NULL DEFAULT 'KRW',
    image_url         VARCHAR(1000),
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by        BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_travel_themes_budget CHECK (max_budget IS NULL OR min_budget IS NULL OR max_budget >= min_budget),
    CONSTRAINT ck_travel_themes_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);
CREATE INDEX idx_travel_themes_status_region ON travel_themes(status, representative_region);
CREATE TRIGGER trg_travel_themes_updated_at BEFORE UPDATE ON travel_themes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE travel_theme_styles (
    travel_theme_id BIGINT NOT NULL REFERENCES travel_themes(travel_theme_id) ON DELETE CASCADE,
    travel_style_id SMALLINT NOT NULL REFERENCES travel_styles(travel_style_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (travel_theme_id, travel_style_id)
);

COMMENT ON TABLE travel_theme_styles IS 'Travel style tags shown on curated theme cards';

CREATE TABLE travel_theme_places (
    travel_theme_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_theme_id       BIGINT NOT NULL REFERENCES travel_themes(travel_theme_id) ON DELETE CASCADE,
    place_id              BIGINT NOT NULL REFERENCES places(place_id),
    day_number            SMALLINT CHECK (day_number IS NULL OR day_number > 0),
    sort_order            SMALLINT NOT NULL CHECK (sort_order > 0),
    recommendation_note   VARCHAR(500),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_travel_theme_places_place UNIQUE (travel_theme_id, place_id),
    CONSTRAINT uk_travel_theme_places_order UNIQUE (travel_theme_id, sort_order)
);

CREATE TABLE place_sync_jobs (
    place_sync_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    provider          VARCHAR(30) NOT NULL,
    job_type          VARCHAR(20) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_count   INTEGER NOT NULL DEFAULT 0 CHECK (requested_count >= 0),
    processed_count   INTEGER NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    created_count     INTEGER NOT NULL DEFAULT 0 CHECK (created_count >= 0),
    updated_count     INTEGER NOT NULL DEFAULT 0 CHECK (updated_count >= 0),
    failed_count      INTEGER NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
    error_summary     VARCHAR(1000),
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_place_sync_jobs_type CHECK (job_type IN ('FULL', 'INCREMENTAL', 'MANUAL')),
    CONSTRAINT ck_place_sync_jobs_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL_FAILED', 'FAILED')),
    CONSTRAINT ck_place_sync_jobs_counts CHECK (processed_count <= requested_count AND created_count + updated_count + failed_count <= processed_count),
    CONSTRAINT ck_place_sync_jobs_period CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);
CREATE INDEX idx_place_sync_jobs_status_created ON place_sync_jobs(status, created_at DESC);
CREATE INDEX idx_place_sync_jobs_provider_created ON place_sync_jobs(provider, created_at DESC);

CREATE TABLE place_sync_errors (
    place_sync_error_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_sync_job_id   BIGINT NOT NULL REFERENCES place_sync_jobs(place_sync_job_id) ON DELETE CASCADE,
    external_place_id   VARCHAR(100),
    error_code          VARCHAR(100),
    error_message       VARCHAR(1000) NOT NULL,
    raw_payload         JSONB,
    retry_status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count         SMALLINT NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    last_retried_at     TIMESTAMPTZ,
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_place_sync_errors_retry_status CHECK (retry_status IN ('PENDING', 'RETRIED', 'RESOLVED', 'IGNORED'))
);
CREATE INDEX idx_place_sync_errors_job_status ON place_sync_errors(place_sync_job_id, retry_status);

CREATE TABLE admin_audit_logs (
    admin_audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    action_type        VARCHAR(30) NOT NULL,
    target_type        VARCHAR(50) NOT NULL,
    target_id          VARCHAR(100),
    before_data        JSONB,
    after_data         JSONB,
    request_id         VARCHAR(100),
    ip_address         INET,
    user_agent         VARCHAR(500),
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_admin_audit_logs_admin_time ON admin_audit_logs(admin_user_id, occurred_at DESC);
CREATE INDEX idx_admin_audit_logs_target ON admin_audit_logs(target_type, target_id, occurred_at DESC);
CREATE INDEX idx_admin_audit_logs_request ON admin_audit_logs(request_id);

COMMENT ON TABLE travel_themes IS 'Curated theme cards registered from the administrator screen';
COMMENT ON TABLE travel_theme_places IS 'Ordered places composing a curated travel theme';
COMMENT ON TABLE place_sync_jobs IS 'External place synchronization job history';
COMMENT ON TABLE place_sync_errors IS 'Record-level failures from place synchronization jobs';
COMMENT ON TABLE admin_audit_logs IS 'Immutable administrator and system action audit trail';


-- =========================================================
-- V7__ticket_reservation.sql
-- =========================================================

-- All My Trips Flyway migration: V7__ticket_reservation
-- Target: PostgreSQL 16+

CREATE TABLE ticket_products (
    ticket_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id          BIGINT NOT NULL REFERENCES places(place_id),
    name              VARCHAR(150) NOT NULL,
    description       TEXT,
    sale_start_at     TIMESTAMPTZ NOT NULL,
    sale_end_at       TIMESTAMPTZ NOT NULL,
    usage_start_date  DATE NOT NULL,
    usage_end_date    DATE NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_products_sale_period CHECK (sale_end_at > sale_start_at),
    CONSTRAINT ck_ticket_products_usage_period CHECK (usage_end_date >= usage_start_date),
    CONSTRAINT ck_ticket_products_status CHECK (status IN ('DRAFT', 'ON_SALE', 'SOLD_OUT', 'ENDED', 'CANCELLED'))
);
CREATE INDEX idx_ticket_products_place_status ON ticket_products(place_id, status);
CREATE INDEX idx_ticket_products_sale_period ON ticket_products(sale_start_at, sale_end_at);
CREATE TRIGGER trg_ticket_products_updated_at BEFORE UPDATE ON ticket_products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_product_options (
    ticket_product_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_product_id        BIGINT NOT NULL REFERENCES ticket_products(ticket_product_id) ON DELETE CASCADE,
    name                     VARCHAR(150) NOT NULL,
    description              VARCHAR(1000),
    unit_price               NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    currency_code            CHAR(3) NOT NULL DEFAULT 'KRW',
    max_quantity_per_user    SMALLINT NOT NULL DEFAULT 4 CHECK (max_quantity_per_user > 0),
    sort_order               SMALLINT NOT NULL DEFAULT 1 CHECK (sort_order > 0),
    is_active                BOOLEAN NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ticket_product_options_name UNIQUE (ticket_product_id, name),
    CONSTRAINT uk_ticket_product_options_order UNIQUE (ticket_product_id, sort_order)
);
CREATE TRIGGER trg_ticket_product_options_updated_at BEFORE UPDATE ON ticket_product_options
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_time_slots (
    ticket_time_slot_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_product_option_id  BIGINT NOT NULL REFERENCES ticket_product_options(ticket_product_option_id) ON DELETE CASCADE,
    usage_date                DATE NOT NULL,
    start_time                TIME,
    end_time                  TIME,
    status                    VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ticket_time_slots UNIQUE NULLS NOT DISTINCT (ticket_product_option_id, usage_date, start_time),
    CONSTRAINT ck_ticket_time_slots_period CHECK (end_time IS NULL OR start_time IS NULL OR end_time > start_time),
    CONSTRAINT ck_ticket_time_slots_status CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);
CREATE INDEX idx_ticket_time_slots_date_status ON ticket_time_slots(usage_date, status);
CREATE TRIGGER trg_ticket_time_slots_updated_at BEFORE UPDATE ON ticket_time_slots
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_inventory (
    ticket_time_slot_id BIGINT PRIMARY KEY REFERENCES ticket_time_slots(ticket_time_slot_id) ON DELETE CASCADE,
    total_quantity      INTEGER NOT NULL CHECK (total_quantity >= 0),
    reserved_quantity   INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    version             BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_inventory_quantities CHECK (reserved_quantity <= total_quantity)
);
CREATE TRIGGER trg_ticket_inventory_updated_at BEFORE UPDATE ON ticket_inventory
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE reservations (
    reservation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_number VARCHAR(30) NOT NULL UNIQUE,
    user_id            BIGINT NOT NULL REFERENCES users(user_id),
    status             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_amount       NUMERIC(15,2) NOT NULL CHECK (total_amount >= 0),
    currency_code      CHAR(3) NOT NULL DEFAULT 'KRW',
    expires_at         TIMESTAMPTZ,
    confirmed_at       TIMESTAMPTZ,
    cancelled_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'USED'))
);
CREATE INDEX idx_reservations_user_status_created ON reservations(user_id, status, created_at DESC);
CREATE INDEX idx_reservations_status_expires ON reservations(status, expires_at);
CREATE TRIGGER trg_reservations_updated_at BEFORE UPDATE ON reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE reservation_items (
    reservation_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      BIGINT NOT NULL REFERENCES reservations(reservation_id) ON DELETE CASCADE,
    ticket_time_slot_id BIGINT NOT NULL REFERENCES ticket_time_slots(ticket_time_slot_id),
    product_name        VARCHAR(150) NOT NULL,
    option_name         VARCHAR(150) NOT NULL,
    usage_date          DATE NOT NULL,
    usage_start_time    TIME,
    quantity            SMALLINT NOT NULL CHECK (quantity > 0),
    unit_price          NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    line_amount         NUMERIC(15,2) NOT NULL CHECK (line_amount >= 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reservation_items_slot UNIQUE (reservation_id, ticket_time_slot_id),
    CONSTRAINT ck_reservation_items_line_amount CHECK (line_amount = unit_price * quantity)
);
CREATE INDEX idx_reservation_items_slot ON reservation_items(ticket_time_slot_id);

CREATE TABLE payments (
    payment_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id       BIGINT NOT NULL REFERENCES reservations(reservation_id),
    idempotency_key      VARCHAR(100) NOT NULL UNIQUE,
    provider             VARCHAR(30) NOT NULL,
    provider_payment_key VARCHAR(100),
    method               VARCHAR(20) NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'READY',
    amount               NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
    currency_code        CHAR(3) NOT NULL DEFAULT 'KRW',
    failure_code         VARCHAR(50),
    failure_message      VARCHAR(500),
    requested_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at          TIMESTAMPTZ,
    cancelled_at         TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payments_provider_key UNIQUE (provider, provider_payment_key),
    CONSTRAINT ck_payments_method CHECK (method IN ('CARD', 'TRANSFER', 'VIRTUAL_ACCOUNT', 'EASY_PAY')),
    CONSTRAINT ck_payments_status CHECK (status IN ('READY', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED'))
);
CREATE INDEX idx_payments_reservation_status ON payments(reservation_id, status);
CREATE TRIGGER trg_payments_updated_at BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE issued_tickets (
    issued_ticket_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_item_id     BIGINT NOT NULL REFERENCES reservation_items(reservation_item_id),
    ticket_number           VARCHAR(50) NOT NULL UNIQUE,
    verification_token_hash CHAR(64) NOT NULL UNIQUE,
    issue_method            VARCHAR(20) NOT NULL DEFAULT 'MOBILE',
    status                  VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
    valid_from              TIMESTAMPTZ NOT NULL,
    valid_until             TIMESTAMPTZ NOT NULL,
    issued_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at                 TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    replaced_by_ticket_id   BIGINT UNIQUE REFERENCES issued_tickets(issued_ticket_id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_issued_tickets_method CHECK (issue_method IN ('MOBILE', 'EMAIL', 'PRINT', 'ONSITE')),
    CONSTRAINT ck_issued_tickets_status CHECK (status IN ('ISSUED', 'USED', 'CANCELLED', 'EXPIRED', 'REPLACED')),
    CONSTRAINT ck_issued_tickets_validity CHECK (valid_until > valid_from),
    CONSTRAINT ck_issued_tickets_used_at CHECK (used_at IS NULL OR used_at >= issued_at),
    CONSTRAINT ck_issued_tickets_cancelled_at CHECK (cancelled_at IS NULL OR cancelled_at >= issued_at)
);
CREATE INDEX idx_issued_tickets_item ON issued_tickets(reservation_item_id);
CREATE INDEX idx_issued_tickets_status_valid_until ON issued_tickets(status, valid_until);
CREATE TRIGGER trg_issued_tickets_updated_at BEFORE UPDATE ON issued_tickets
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_validation_logs (
    ticket_validation_log_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issued_ticket_id           BIGINT REFERENCES issued_tickets(issued_ticket_id),
    validator_user_id          BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    presented_token_fingerprint CHAR(64),
    validation_result          VARCHAR(20) NOT NULL,
    validation_channel         VARCHAR(20) NOT NULL DEFAULT 'ADMIN_WEB',
    device_id                  VARCHAR(100),
    failure_reason             VARCHAR(500),
    metadata                   JSONB,
    validated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_validation_logs_result CHECK (validation_result IN ('SUCCESS', 'NOT_FOUND', 'ALREADY_USED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_ticket_validation_logs_channel CHECK (validation_channel IN ('ADMIN_WEB', 'MOCK_SCANNER', 'API'))
);
CREATE INDEX idx_ticket_validation_logs_ticket_time ON ticket_validation_logs(issued_ticket_id, validated_at DESC);
CREATE INDEX idx_ticket_validation_logs_validator_time ON ticket_validation_logs(validator_user_id, validated_at DESC);
CREATE INDEX idx_ticket_validation_logs_result_time ON ticket_validation_logs(validation_result, validated_at DESC);
CREATE INDEX idx_ticket_validation_logs_fingerprint ON ticket_validation_logs(presented_token_fingerprint);

COMMENT ON TABLE ticket_products IS 'Reservable attraction, festival, and activity ticket groups';
COMMENT ON TABLE ticket_product_options IS 'Selectable price options shown on the ticket detail screen';
COMMENT ON TABLE ticket_time_slots IS 'Bookable usage dates and times for a ticket option';
COMMENT ON TABLE ticket_inventory IS 'Per-time-slot inventory aggregate for concurrency control';
COMMENT ON TABLE reservations IS 'Mock ticket reservation orders';
COMMENT ON TABLE reservation_items IS 'Reservation line item snapshots';
COMMENT ON TABLE payments IS 'Idempotent mock payment attempts and results';
COMMENT ON TABLE issued_tickets IS 'Individually issued mock electronic tickets';
COMMENT ON TABLE ticket_validation_logs IS 'Mock QR and barcode ticket validation attempts';

CREATE TABLE support_inquiries (
    support_inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category           VARCHAR(30) NOT NULL,
    title              VARCHAR(150) NOT NULL,
    content            VARCHAR(3000) NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_support_inquiries_category CHECK (category IN ('TRIP_PLAN', 'AI_PLAN', 'PLACE_FAVORITE', 'BOOKING', 'ACCOUNT', 'ERROR', 'OTHER')),
    CONSTRAINT ck_support_inquiries_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'ANSWERED', 'CLOSED'))
);
CREATE INDEX idx_support_inquiries_user_created ON support_inquiries(user_id, created_at DESC);
CREATE INDEX idx_support_inquiries_status_created ON support_inquiries(status, created_at ASC);
CREATE TRIGGER trg_support_inquiries_updated_at BEFORE UPDATE ON support_inquiries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE support_inquiries IS 'Customer support inquiries submitted by members';

CREATE TABLE support_replies (
    support_reply_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_inquiry_id BIGINT NOT NULL REFERENCES support_inquiries(support_inquiry_id) ON DELETE CASCADE,
    admin_user_id      BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    content            VARCHAR(3000) NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_support_replies_inquiry_created
    ON support_replies(support_inquiry_id, created_at);

COMMENT ON TABLE support_replies IS 'Administrator replies to customer support inquiries';
